### ISSUE TITLE
Autoren/Editoren mit Namenprefix (#5)

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#14]
Hier kommt es zu folgendem Problem:
Hennervon Hesberg, Römische Baukunst, Beck’s archäologische Biblio- thek (München 2005)
--> Zusammenschreiben von Vorname und Namensprefix -> Die Sortierung erfolgt hier unter "H" (nicht unter "v")

@Book{Hesberg_2005,
  Title                    = {Römische Baukunst},
  Author                   = {von Hesberg, Henner},
  Publisher                = {Beck},
Location = {München},
  Series                   = {Beck's archäologische Bibliothek},
  Year                     = {2005},
}

Formatiert man allerdings den Namen um: Author = {{von Hesberg}, Henner}, dann wird ein Leerzeichen zwischen Vornamen und Namensprefix gesetzt, allerdings wird dann unter "v" sortiert, d.h. Namensprefix und Nachname werden als Nachname aufgefasst

**Comment by giovannotti** [comment]
Gefixed, bitte schließen, wenn es passt.
