### ISSUE TITLE
\labelwidth in der Bibliographie zu schmal

### ISSUE THREAD

**Issue by giovannotti** [giovannotti/biblatex-archaeologie#17]
Die Breite der Autor-Jahr-Zitate in der Bibliographie ist zu schmal. Wenn da 3 Namen erscheinen, ist der Platz zu eng. Ich hatte dafür mal einen Zeilensprung reingearbeitet. Aber da du an dem Bibliographie-Layout noch herumgebastelst hast, trau ich mich da jetzt nicht ran (was hat es z.B. mit der Option shorthandwidthbool auf sich? etc.)

Vorschlag (außer, du weisst was besseres):
letzte Zeile der \defbibenvironment{bibliography} anstelle von
{\item }
in
{\item  \ifbool{bbx:daiverweis}{}{mbox{}\newline}}}
umändern.
Und dann muss man wohl nur noch an \leftmargin bzw. \labelwidth rumspielen. Oder?

**Comment by LukasCBossert** [comment]
Du hast vollkommen Recht, es ist momentan noch nicht optimal. Die Breite des linken Bereichs richtet sich nach der Breite der Shorthands: Längste Shorthand definiert den Bereich.
Das müsste man für alle nicht shorthands (die ja NICHT mit \printshorthand geplottet werden) wieder aufheben. 
Ich weiß noch nicht, wie ich in deiner vorgeschlagenen Zeile umsetzen kann, dass für die „Sekundärliteratur“ eine extra Zeile eingefügt wird. Aber ich mache mich jetzt dran.


Am 29.06.2015 um 15:14 schrieb Johannes <notifications@github.com>:

Die Breite der Autor-Jahr-Zitate in der Bibliographie ist zu schmal. Wenn da 3 Namen erscheinen, ist der Platz zu eng. Ich hatte dafür mal einen Zeilensprung reingearbeitet. Aber da du an dem Bibliographie-Layout noch herumgebastelst hast, trau ich mich da jetzt nicht ran (was hat es z.B. mit der Option shorthandwidthbool auf sich? etc.)

Vorschlag (außer, du weisst was besseres):
letzte Zeile der \defbibenvironment{bibliography} anstelle von
{\item }
in
{\item \ifbool{bbx:daiverweis}{}{mbox{}\newline}}}
umändern.
Und dann muss man wohl nur noch an \leftmargin bzw. \labelwidth rumspielen. Oder?

**Comment by LukasCBossert** [comment]
wofür shorthandwidthbool ist, weiß ich auch nicht genau, das ist aus „standard-dw“ übernommen. aber vielleicht kann man da was drehen und schreiben

über einen bool-bbx zusteuern geht nicht mehr, da ja „dai“ standard ist. und man ja nicht nur für die noch kommende Option „dai-verweis“ die extra Zeile für das Namelabel haben möchte?!


Am 29.06.2015 um 15:14 schrieb Johannes <notifications@github.com>:

Die Breite der Autor-Jahr-Zitate in der Bibliographie ist zu schmal. Wenn da 3 Namen erscheinen, ist der Platz zu eng. Ich hatte dafür mal einen Zeilensprung reingearbeitet. Aber da du an dem Bibliographie-Layout noch herumgebastelst hast, trau ich mich da jetzt nicht ran (was hat es z.B. mit der Option shorthandwidthbool auf sich? etc.)

Vorschlag (außer, du weisst was besseres):
letzte Zeile der \defbibenvironment{bibliography} anstelle von
{\item }
in
{\item \ifbool{bbx:daiverweis}{}{mbox{}\newline}}}
umändern.
Und dann muss man wohl nur noch an \leftmargin bzw. \labelwidth rumspielen. Oder?

**Comment by LukasCBossert** [comment]
Zwischenlösung: 
  \AtBeginBibliography{%
   \renewbibmacro{begentry}{% 
       {\ifbool{cbx:unbekannt}{	\usebibmacro{shorthand+year}}{%		%unbekannte Autoren
					\ifboolexpr{bool {cbx:antik} 
									or bool {cbx:frgantik} 
									or bool {cbx:frg} 
									or bool {cbx:nurshorthand}}%
							{\printfield[shorthandwidth]{shorthand}}%
							{\printtext{\printnames[cite:author]{labelname}}%
     				\addspace\printtext[\ifbool{cbx:jahrinklammern}{parens}{}]{%
       					 \printfield{labelyear}\printfield{extrayear}\\}%
       					 }}%
							}%
}}


Feintuning kommt, dann kommt der commit.

**Comment by giovannotti** [comment]
bin gespannt!

**Comment by LukasCBossert** [comment]
Es ist momentan so gelöst, dass Zeilenumsprung für Sekundärliteratur und \hspace*{3em} bei den anderen. Schöner wäre, wenn alles außer Sek.-Lit. so wie zuvor wäre. Ich bleibe dran.

**Comment by giovannotti** [comment]
stimmt, und dai-verweis braucht dann in der Sekündar, äh Sekundär-Lit. gar kein shorthand/labelname sondern nur das bin-item. Oder?

**Comment by LukasCBossert** [comment]
ja, bei dai-verweis fällt der labelname weg (aber für Primärlit. bleibt shorthand und für Sigel auch).

momentan ist es so gelöst: https://github.com/giovannotti/biblatex-archaeologie/blob/WorkInProgress/MWE_archaeologie.pdf
Also fast erledigt.
Aber ich will, dass bei Sekundärlit, der labelname kleiner als shorthandwidth ist, auf der gleichen Zeile beginnt, und nur wenn labelname länger ist, ein Absatz erfolgt. momentan kommt in Sek.-Lit. immer ein Absatz.

**Comment by giovannotti** [comment]
sehr geil. du spitzfindiger Hund! 😄 (um Missverständnissen vorzubeugen: In Bayern drückt man so seine Bewunderung für Cleverness aus!)
 😉

**Comment by LukasCBossert** [comment]
Vielen Dank. ich nehme das Kompliment sehr gerne an - dann lohnt es sich, die halbe nacht um die Ohren zu schlagen.
Allerdings habe ich mich wegen des Problems mit shorthandwidth/labelwidth an einen Profi gewandt. mal schauen, ob er eine Lösung hat.


Am 30.06.2015 um 10:52 schrieb Johannes <notifications@github.com>:

sehr geil. du spitzfindiger Hund! 😄 (um Missverständnissen vorzubeugen: In Bayern drückt man so seine Bewunderung für Cleverness aus!)
😉

**Comment by LukasCBossert** [comment]
Endlich wieder Neuigkeiten: Dank externer Hilfe konnte ich das Problem mit \labelwidth und Zeilenumsprung lösen. (siehe commit)


\newbibmacro{labelwidthbib}{%
 \printtext{\printnames[cite:author]{labelname}}%
     	\addspace\printtext[\ifbool{cbx:jahrinklammern}{parens}{}]{%
       	 \printfield{labelyear}\printfield{extrayear}}}

%%%%%%%% Bibliographielayout für Autor-Jahr-Auflistung %%%%%%%%%% 
\def\labelwidthbib{{\usebibmacro{labelwidthbib}}}%
\StrLen{\labelwidthbib}[\labelwidthlength]%

\newsavebox\arch@labelbox%
\AtBeginBibliography{%
  \renewbibmacro{begentry}{% 
    \sbox\arch@labelbox{\usebibmacro{labelwidthbib}}%
    \ifboolexpr{bool {cbx:antik}%
	     or bool {cbx:frgantik}% 
	     or bool {cbx:frg}% 
	     or bool {cbx:nurshorthand}}%
      {}%						%hier Länge für Abstand angeben
      {\ifdim\shorthandwidth < .9\wd\arch@labelbox\newline\fi}}}%%% bspw. <.9 für geringeren Abstand




Allerdings ergibt sich nun ein anderes Problem, dass Einträge ohne Author oder Editor mit einem Komma beginnen.
Dafür werde ich ein neues Issue eröffnen.
