### ISSUE TITLE
Option "nurinit" global/lokal-manuell

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#19]
Die Option "nurinit" muss noch auf standard gesetzt werden.

ABER.... 

wie wäre es, die Option so umzuformulieren, dass die Funktion von "nurinit" standardmäßig aktiviert ist und nur Optional (über bsp. "bibvollername" ) ansteuerbar, dass die Namen in der Bibliographie ausgeschrieben werden. 
Dann braucht man keine Option für den DAI-STandard, sondern kann über eine Option vom Standard abweichen!?

**Comment by giovannotti** [comment]
wird gemacht.

**Comment by LukasCBossert** [comment]
super!

Am 01.07.2015 um 12:36 schrieb Johannes <notifications@github.com>:

wird gemacht.

**Comment by LukasCBossert** [comment]
gelöst
