### ISSUE TITLE
bibnamedash - Klärungsbedarf

### ISSUE THREAD

**Issue by giovannotti** [giovannotti/biblatex-archaeologie#2]
was gibt es beim bibnamedash genaues zu beachten?

Ich denke an folgendes:
- wenn dai oder autorjahr, dann kein bibnamedash;
- wenn autor-titel-jahr bzw. vollzitat (haben wir das überhaupt?), dann bibnamedash

siehe ich das richtig?

**Comment by LukasCBossert** [comment]
Ich glaube, ich habe mich beim ekrlären vertan: Es taucht jetzt kein bibnamedash mehr auf, das konnte ich lösen.
aber die Autoren werden nicht mit „—„ getrennt, sondern mit Komma und „und“. Das konnte ich nicht umstellen.


Am 22.06.2015 um 14:24 schrieb Johannes <notifications@github.com>:

was gibt es beim bibnamedash genaues zu beachten?

Ich denke an folgendes:

wenn dai oder autorjahr, dann kein bibnamedash;
wenn autor-titel-jahr bzw. vollzitat (haben wir das überhaupt?), dann bibnamedash
siehe ich das richtig?

**Comment by giovannotti** [comment]
Das hängt im Moment ja alles an autorjahr=true. Ich ziehe diese Zitierweise ("–" etc.) aus dem cbx-autorjahr-bool raus un verlagere es in den dai-bool. dann bleibt der cbx-autorjahr-bool für den fall, falls man nicht dai möchte, aber dennoch autor-jahr (hier gibt es dann auch Autorentrennung mit Komma und "und"). Ok?

**Comment by LukasCBossert** [comment]
hm - hab es noch nicht ganz kapiert - werde es aber dann in der MWE sehen.
Klingt aber logisch :)


Am 22.06.2015 um 14:41 schrieb Johannes <notifications@github.com>:

Das hängt im Moment ja alles an autorjahr=true. Ich ziehe diese Zitierweise ("–" etc.) aus dem cbx-autorjahr-bool raus un verlagere es in den dai-bool. dann bleibt der cbx-autorjahr-bool für den fall, falls man nicht dai möchte, aber dennoch autor-jahr (hier gibt es dann auch Autorentrennung mit Komma und "und"). Ok?

**Comment by giovannotti** [comment]
doch noch eine Nachfrage: willst du den bibnamedash überhaupt noch irgendwann? 
Möglichkeiten, wo es sinvoll wäre:
- DAI, kein Autorjahr
- kein DAI, kein Autorjahr

Vorschlag:
- bibnamedash, wenn autorjahr=false
- Trennung von Autoren mit "--", wenn dai=true, sonst mit Komma und "und" (dann hätte man zudem bei autorjahr=true eine Autorjahr-Trennung mit Komma und "und")

oder soll er ganz raus?

**Comment by LukasCBossert** [comment]
Sehr gerne wie du vorschlägst - du habe ich es mir auch vorgestellt. Das lässt uns am meisten Spielraum für verschiedene Darstellungsmodi.


Am 22.06.2015 um 15:31 schrieb Johannes <notifications@github.com>:

doch noch eine Nachfrage: willst du den bibnamedash überhaupt noch irgendwann? 
Möglichkeiten, wo es sinvoll wäre:

DAI, kein Autorjahr
kein DAI, kein Autorjahr
Vorschlag:

bibnamedash, wenn autorjahr=false
Trennung von Autoren mit "--", wenn dai=true, sonst mit Komma und "und" (dann hätte man zudem bei autorjahr=true eine Autorjahr-Trennung mit Komma und "und")
oder soll er ganz raus?

**Comment by LukasCBossert** [comment]
Sehr gerne wie du vorschlägst - so(!) habe ich es mir auch vorgestellt. Das lässt uns am meisten Spielraum für verschiedene Darstellungsmodi.


Am 22.06.2015 um 15:34 schrieb Lukas C. Bossert <lukascb@me.com>:

Sehr gerne wie du vorschlägst - du habe ich es mir auch vorgestellt. Das lässt uns am meisten Spielraum für verschiedene Darstellungsmodi.


Am 22.06.2015 um 15:31 schrieb Johannes <notifications@github.com <mailto:notifications@github.com>>:

doch noch eine Nachfrage: willst du den bibnamedash überhaupt noch irgendwann? 
Möglichkeiten, wo es sinvoll wäre:

DAI, kein Autorjahr
kein DAI, kein Autorjahr
Vorschlag:

bibnamedash, wenn autorjahr=false
Trennung von Autoren mit "--", wenn dai=true, sonst mit Komma und "und" (dann hätte man zudem bei autorjahr=true eine Autorjahr-Trennung mit Komma und "und")
oder soll er ganz raus?

**Comment by LukasCBossert** [comment]
was ich auch noch nicht rausgefunden habe, ob dies möglich ist:
wenn dai=true, dass dann andere bbx/cbx-optionen entsprechend auf false oder true gestellt werden, egal wie sie in der Präambel gesetzt sind. Dann muss man dies nicht mehr manuell umstellen.

bspw.
	- dai = true (dann zugleich autorjahr=true)

Weißt du da was dazu?

Am 22.06.2015 um 15:31 schrieb Johannes <notifications@github.com>:

doch noch eine Nachfrage: willst du den bibnamedash überhaupt noch irgendwann? 
Möglichkeiten, wo es sinvoll wäre:

DAI, kein Autorjahr
kein DAI, kein Autorjahr
Vorschlag:

bibnamedash, wenn autorjahr=false
Trennung von Autoren mit "--", wenn dai=true, sonst mit Komma und "und" (dann hätte man zudem bei autorjahr=true eine Autorjahr-Trennung mit Komma und "und")
oder soll er ganz raus?

**Comment by giovannotti** [comment]
Schau dir mal die 4 Zeilen ab Zeile 68 in der bbx an. Das müssten, nach meiner Interpretation, zwei solche Befehle sein, habe es aber selbst noch nicht ausprobiert. Oder irre ich mich?

**Comment by LukasCBossert** [comment]
hast du deinen Code schon hochgeladen?
Sonst schau ich in den aktuellen.


Am 22.06.2015 um 16:01 schrieb Johannes <notifications@github.com>:

Schau dir mal die 4 Zeilen ab Zeile 68 in der bbx an. Das müssten, nach meiner Interpretation, zwei solche Befehle sein, habe es aber selbst noch nicht ausprobiert. Oder irre ich mich?

**Comment by LukasCBossert** [comment]
Das ist in der Tat interessant. Diese Zeilen habe ich aus „standard-dw“ übernommen (bei diesen Zeilen (57–83) müsste man mal ausmisten, was wir wirklich brauchen und nutzen.

ich versuche "\DeclareBibliographyOption{shorthandinbib}[true]{%
  \csuse{bool#1}{bbx:shorthandinbib}}“ mal nachzuvoll ziehen, bzw. dann für „dai=treu“ (=autorjahr=true) umzusetzen.


Am 22.06.2015 um 16:01 schrieb Johannes <notifications@github.com>:

Schau dir mal die 4 Zeilen ab Zeile 68 in der bbx an. Das müssten, nach meiner Interpretation, zwei solche Befehle sein, habe es aber selbst noch nicht ausprobiert. Oder irre ich mich?

**Comment by LukasCBossert** [comment]
Danke! Manchmal reichen mir kleine Hinweise, damit ich weiterkomme … :-)
Schau dir in der gerade hochgeladenen Version die Zeilen 34-40 an. Ich denke, ich habe es gelöst.
Kann man aber noch schöner machen. Jetzt muss man in der Präambel DAI-alles=true laden, dann wird „dai=true UND autorjahr=true“ geladen. Genial!


Am 22.06.2015 um 16:01 schrieb Johannes <notifications@github.com>:

Schau dir mal die 4 Zeilen ab Zeile 68 in der bbx an. Das müssten, nach meiner Interpretation, zwei solche Befehle sein, habe es aber selbst noch nicht ausprobiert. Oder irre ich mich?

—
Reply to this email directly or view it on GitHub <https://github.com/giovannotti/biblatex-archaeologie/issues/2#issuecomment-114113195>.



LUKAS C. BOSSERT

**Comment by LukasCBossert** [comment]
habe gerade ein update hochgeladen.
option dai=true ist nun „global“ und beinhaltet weitere suboptionen (autorjahr, citeinit, etc.)


Am 22.06.2015 um 16:01 schrieb Johannes <notifications@github.com>:

Schau dir mal die 4 Zeilen ab Zeile 68 in der bbx an. Das müssten, nach meiner Interpretation, zwei solche Befehle sein, habe es aber selbst noch nicht ausprobiert. Oder irre ich mich?

**Comment by giovannotti** [comment]
super! ich schau es mir morgen mal an. mein commit kommt dann auch

**Comment by LukasCBossert** [comment]
prima. bin gespannt. 
Habe gerade noch einen kleinen Fehler wg. bibnamedash entdeckt., aber da bist du ja eh dran.


Am 22.06.2015 um 18:29 schrieb Johannes <notifications@github.com>:

super! ich schau es mir morgen mal an. mein commit kommt dann auch
