### ISSUE TITLE
Copyright / README

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#28]
Copyright in cbx und bbx einfügen

**Comment by giovannotti** [comment]
Lizenz in der Form, oder was hättest du gerne?

```
  %% pig.dtx
  %% Copyright 2005 M. Y. Name
  %
  % This work may be distributed and/or modified under the
  % conditions of the LaTeX Project Public License, either version 1.3
  % of this license or (at your option) any later version.
  % The latest version of this license is in
  %   http://www.latex-project.org/lppl.txt
  % and version 1.3 or later is part of all distributions of LaTeX
  % version 2005/12/01 or later.
  %
  % This work has the LPPL maintenance status 'maintained'.
  % 
  % The Current Maintainer of this work is M. Y. Name.
  %
  % This work consists of the files pig.dtx and pig.ins
  % and the derived file pig.sty.
```

siehe https://latex-project.org/lppl/

**Comment by LukasCBossert** [comment]
bspw:

geschichtsfrkl: a biblatex bibliography style for (German) historians with lots of options

Copyright (C) 2011--2012 Jonathan Zachhuber
E-mail: jonathan.zachhuber@gmail.com

Files:
geschichtsfrkl.ins      Batch file, run through LaTeX
geschichtsfrkl.dtx      Docstrip archive, run through (Xe)LaTeX
bbx/geschichtsfrkl.bbx  biblatex bibliography style file, generated by geschichtsfrkl.ins from geschichtsfrkl.dtx
cbx/geschichtsfrkl.cbx  biblatex citation style file, generated by geschichtsfrkl.ins from geschichtsfrkl.dtx
geschichtsfrkl.pdf      Package documentation; can also be generated from geschichtsfrkl.dtx
README                  This file

This material is subject to the LaTeX Project Public License. See
http://www.ctan.org/tex-archive/help/Catalogue/licenses.lppl.html for the
details of that license.

For more information on the package, see the documentation in geschichtsfrkl.pdf (unfortunately, it is in German, especially the examples should be fairly self-explanatory, though; feel free to contact me for translations, though).



das sollte schon reichen.

**Comment by giovannotti** [comment]
ok

**Comment by LukasCBossert** [comment]
Vorschlag:

```
archaeologie: biblatex fuer Archaeologen, Historiker und Philologen (Deutsch und Englisch)

Copyright (c) 2015 Lukas C. Bossert | Johannes Friedl
Email: lukas@digitales-altertum.de

Dateien: 
archaeologie.pdf
archaeologie.cbx
archaeologie.bbx
archaeologie.lbx
archaeologie_english.lbx
dai-abkuerzungen.bib

This material is subject to the LaTeX Project Public License. See
http://www.ctan.org/tex-archive/help/Catalogue/licenses.lppl.html for the
details of that license.

```

**Comment by LukasCBossert** [comment]
Für die Readme:
```
##########################
##      bibLaTeX-archaeologie     ##
#########################
Version: [2015/11/11 v1.2]

archaeologie: biblatex fuer Archaeologen, Historiker und Philologen (Deutsch und Englisch)

Copyright (c) 2015 Lukas C. Bossert | Johannes Friedl
Email: lukas@digitales-altertum.de

Der Stil setzt die Zitations- und Bibliographievorgaben des Deutschen Archäologischen Instituts (DAI) (Stand 2014) um. Verschiedene zusätzliche Optionen erlauben das Erscheinungsbild jedoch auch zu verändern, um eigenen Vorlieben anzupassen.
****
This citation-style covers the citation and bibliography rules of the German Archaeology Institute. 
Various options are available to change and adjust the outcome according to one’s own preferences.
****


Zum Stil gehören:
archaeologie.pdf
archaeologie.cbx
archaeologie.bbx
archaeologie.dbx
archaeologie_ngerman.lbx
archaeologie_english.lbx
dai-abkuerzungen.bib


 This work may be distributed and/or modified under the
 conditions of the LaTeX Project Public License, either version 1.3
 of this license or (at your option) any later version.
 The latest version of this license is in
 http://www.latex-project.org/lppl.txt
 and version 1.3 or later is part of all distributions of LaTeX
 version 2005/12/01 or later.
```

@giovannotti willst du deine/eine Mailadresse eintragen?

**Comment by moewew** [comment]
Seht euch zum Thema Lizenzierung http://www.texdev.net/2012/05/04/the-lppl-maintainer-or-author-maintained/ an. 

Der Block

```
  % This work has the LPPL maintenance status 'maintained'.
  % 
  % The Current Maintainer of this work is M. Y. Name.
````

kann also durchaus sinnvoll sein.

**Comment by giovannotti** [comment]
Ja, den Maintaining-Status sollten wir reinnehmen. @LukasCBossert, da macht dein Name sehr Sinn und es genügt dann auch deine Mailadresse. So ist das Ganze mit "Digitales Altertum" verknüpft. Das ist doch gut so.
