### ISSUE TITLE
Ein paar kleine Beobachtungen

### ISSUE THREAD

**Issue by moewew** [giovannotti/biblatex-archaeologie#33]
Ich bin vor kurzer Zeit auf diesen schönen Stil gestoßen und bin sowohl von dem Aussehen als auch von den vielen Einstellungsmöglichkeiten beeindruckt. Bei der Betrachtung des Codes sind mir einige Dinge aufgefallen, die ich gerne mitteilen würde, vielleicht sind ja ein paar interessante Dankanstöße dabei.

Statt ein neues Format für Autornamen zu definieren und `bbx:bibvollername` zu verwenden, könnte man auch einfacher `firstinits=true` nutzen (oder eben nicht) und einfach 

```
\DeclareNameAlias{author}{first-last}
\renewcommand*{\multinamedelim}{\daiautorentrennzeichen\addspace}
\renewcommand*{\finalnamedelim}{\multinamedelim}
```

Die `\autorenschriftart` wird in der `.bbx` gar nicht genutzt, die Schrift für Namen würde aber idiomatischer mit `\mkbibnamelast` und Konsorten geändert. Ähnliches gilt für die tatsächlich eingesetzte `\citeautorenschriftart`.

Das Makro `in:` kann auch näher am Standard gehalten werden, soweit ich das sehe, ist das `\addspace` unnötig.

Die Definition des Autor-Makros hebelt die Option `maxbibnames` quasi aus auch `\ifuseauthor` aus dem Standard-`biblatex` verliert seine Wirkung. Gleiches gilt auch für `author/editor`.

Die Definition von

```
\newbibmacro{year}{%
  \iffieldundef{year}{}{\mkbibparens{year}}}%
```

verstehe ich nicht, wird hier nicht nur das Wort "year" in Klammern gesetzt? Aber da es nirgendwo ein `\usebibmacro{year}` gibt, ist das Makro wohl überflüssig.

Den slash in `journal+number+year` bekommt man ohne Abfrage etwas idiomatischer mit

```
\renewbibmacro*{journal+number+year}{%  
  \usebibmacro{journal}%
  \setunit*{\addnbspace}%   
  \printfield{volume}%                          
  \setunit{\addslash}%
  \printfield{number}%      
  \newunit%       
  \printfield{year}%     
}%
```

es wäre eine nette Möglichkeit, dort statt `\addslash` so etwas wie `\volnumdelim` zu schreiben und das den Nutzer selbst ändern zu lassen. Das ist ein häufiger Wunsch bei Nutzern.

Es ist ebenfalls eine nette Idee wäre es, an der Nutzung von `\bibpagespunct` festzuhalten.

Statt
```
\newbibmacro*{signatur}{%
  \iffieldundef{note}{}{\printtext[parens]{\printfield{note}}\nopunct}%
```

müsste es eigentlich ausreichen `\newbibmacro*{signatur}{\printfield{note}}` zu schreiben und den Rest mit `\DeclareFieldFormat{note}{\mkbibparens{#1}\nopunct}` zu erschlagen.

Auch bei `volume` müsste eigentlich
```
\newbibmacro*{volume}{\printfield{volume}\newunit}
```
genug sein.

In `booktitle+volume+editor` wird "hrsg. v." direkt in `\printtext` ausgegeben, eleganter wäre es auch hier einen `\bibstring` zu nutzen.

Das gilt auch für "Rez zu" in `\DeclareBibliographyDriver{review}`.

```
\newbibmacro*{refmaintitle}{%
  \iffieldundef{maintitle}{}{%
    \printfield{maintitle}\setunit*{\addspace}\printfield{volume}%
}}%
```
könnte man auch auf
```
\newbibmacro*{refmaintitle}{\printfield{maintitle}\setunit*{\addspace}\printfield{volume}}%
```
reduzieren.

In

```
\DeclareBibliographyDriver{shorthand}{%
\iffieldundef{title}{\printfield{maintitle}}{\printfield[title]{title}}}
```
sollte das `[title]` in `\printfield[title]{title}` überflüssig sein.

Weiter kann darüber nachgedacht werden, die große Datei `archaeologie.bbx` etwas zu entlasten. Es sollte möglich sein, die `dai-abkuerzungen.bib` direkt als eigene Datei mitzuliefern anstatt sie mit `filecontents` zu erstellen. Außerdem kann es sinnvoll sein, die Sprachfeatures in `\DefineBibliographyStrings` in eigene `.lbx`-Dateien auszulagern.

**Comment by giovannotti** [comment]
Danke für die detaillierte Kritik, super!

**Comment by LukasCBossert** [comment]
Vielen Dank für den Input! 
Von diesem Lob und konstruktiver Kritik wird das Update sehr profitieren.

**Comment by moewew** [comment]
Wenn ich schon dabei bin, kann ich ja noch ein paar Kleinigkeiten abladen.

Die Redefinition
```
\renewbibmacro*{prenote}{%
  \iffieldundef{prenote}{}%
    {\printfield{prenote}%
     \setunit{\addspace}}}%
```

in `archaeologie.cbx` kann durch einfach entfernt werden, der Standard tut schon dasselbe und erlaubt obendrein die Änderung des Trenners mit `\prenotedelim`.

Auch bei `postnote` können wir etwas weniger Wiederholgen erreichen

```
\renewbibmacro*{postnote}{%
  \ifboolexpr{bool {cbx:antik}%
              or bool {cbx:frgantik}%
              or bool {cbx:nurshorthand}%
              }%
    {\setunit{\addspace}}%
    {\newunit}%
  \iffieldundef{postnote}
    {}%
    {\printfield{postnote}%
     \ifbool{cbx:frgantik}
       {\setunit{\addspace}%
        \ifnameundef{shorteditor}%
           {\printnames[frg]{editor}}%
           {\printnames[frg]{shorteditor}}}
       {}}}
```

Dem Feld `namea` kann mit Biber ein schönerer Name gegeben werden, der etwas sprechender ist. Dafür müsstet ihr euch dann aber datamodels und `.dbx`-Dateien ansehen.

Die Option `miturl` sollte eigentlich durch die schon vorhandenen Optionen `url`, `doi`, `eprint` schon implementiert sein, scheint mir also überflüssig. Es ist übrigens so, dass `miturl=falsch` automatisch dafür sorgt, dass backreferences immer unterdrückt werden, egal was die `backref`-Option sagt.

Weiter scheint der 
```
  \iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}%
```
Block nur bei bestimmten Typen und nicht bei allen vorhanden zu sein, in `standard.bbx` haben das alle Typen.

Schließlich scheint mir bei `@incollection`s (`@inbook`s) der `booktitle` nicht richtig zu funktionieren, es wird nur `maintitle` beachtet. In der Tat scheint es mir so, dass in der Beispieldatei `archaeologie.bib` bei den  `@in...`-Einträgen eigentlich immer `booktitle` statt `maintitle` genutzt werden sollte.

Die  Datei `archaeologie.bib` ist bei den Sonderzeichen ein wenig inkonsistent, mal werden sie mit `{\"u}` escaped, dann mit `{\"{u}}` und dann gibt es Einträge die einfach die nicht-ASCII-Zeichen nutzen. Ich würde die Datei in UTF-8 Speichern und die richtigen Zeichen `ü` usw. nutzen, ohne sie zu escapen.

**Comment by LukasCBossert** [comment]
besten Dank für die weiteren Infos und den Input. Ich versuche das so gut wie möglich umzusetzen.

**Comment by LukasCBossert** [comment]
bzgl. maxibibnames=999 siehe #58 - funktioniert nur bedingt.

**Comment by LukasCBossert** [comment]
ich schließe dieses Issue, da die Anmerkungen in den anderen Issues aufgegangen sind und dort abgearbeitet werden.
