### ISSUE TITLE
Definition des Autor-Makros

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#38]
Die Definition des Autor-Makros hebelt die Option maxbibnames quasi aus auch \ifuseauthor aus dem Standard-biblatex verliert seine Wirkung. Gleiches gilt auch für author/editor.

**Comment by LukasCBossert** [comment]
hm, weiß nicht, wie ich das angehen kann/soll.

**Comment by moewew** [comment]
Bei dem `author`-Makro ist das ganz einfach. Wenn man `maxbibnames=999` setzt, um alle Autoren anzuzeigen, könnt ihr euch

```
\renewbibmacro*{author}{%
  \ifnameundef{author}{}{%
        \printnames[][-\value{listtotal}]{author}\newunit%
      }}%
```

sparen.

Die Redefinition von `author/editor` ist auch nicht mehr nötig, wenn wir stattdessen

```
\DeclareFieldFormat{editortype}{\mkbibparens{#1}}
\renewbibmacro*{editor}{%
  \ifboolexpr{
    test \ifuseeditor
    and
    not test {\ifnameundef{editor}}
  }
    {\printnames{editor}%
     \setunit{\addspace}%
     \usebibmacro{editorstrg}%
     \clearname{editor}}
    {}}
```
nutzen. Das reicht noch nicht ganz für die Funktion von `frgantik`, das kann aber mit

```
\DeclareEntryOption{frgantik}[true]{%
  \ifstrequal{#1}{true}{\togglefalse{blx@useauthor}}{}%
  \csuse{bool#1}{cbx:frgantik}
}%
```

sofort nachgerüstet werden. Wenn allerdings `frgantik` nie einen Autor haben, dann kann dort auch die ursprüngliche Definition bleiben.

**Comment by moewew** [comment]
Ich denke außerdem, dass `\DeclareNameFormat{cite:author}` unnötig ist, das Setzen der `\citeautorenschriftart` kann auch mit `\renewcommand*{\mkbibnamelast}[1]{\textsc{#1}}` erreicht werden, das kann auch in der Bibliographie und den Zitaten getrennt geregelt werden mit `\AtBeginBibliography` oder `\AtEveryCite`.

(Bitte beachtet, dass ich im letzten Codeblock oben ein `%` vergessen hatte, das habe ich jetzt wieder zugefügt.)

**Comment by moewew** [comment]
Ich denke auch, dass `cite:name` etwas einfacher gehen könnte, da müsste man vielleicht nur an den `uniquename` Optionen herumspielen. Ich würde immer `labelname` nutzen und dann höchstens `\c@uniquename` manipulieren (`\c@uniquename=0` gibt den Nachnamen, 1 mit Initialen, 2 dann den ganzen Namen). `cite:name` scheint auch nur in `\citeauthor` genutzt zu werden. Da könnte man notfalls sogar eine `\renewcommand*{\mkbibnamelast}[1]{#1}` einfügen, um `\citeauthor` immer in derselben Schriftart zu haben.

**Comment by LukasCBossert** [comment]
`maxibibnames=999`siehe #58

**Comment by LukasCBossert** [comment]
bzgl:  `\renewcommand*{\mkbibnamelast}[1]{\textsc{#1}}` 

Ich habe es umgesetzt und festgestellt, dass mit dieser Funktion auch die Nachnamen in der gesamten Bibliographie in SmallCaps geschrieben werden. Aber es sollen nur die Labels in SC stehen.

**Comment by moewew** [comment]
Mit der Änderung in https://github.com/giovannotti/biblatex-archaeologie/issues/58 funktioniert es zumindest so, dass `\AtEveryCite{\renewcommand*{\mkbibnamelast}[1]{\textsc{#1}}}` genau das Gewünschte tut.

**Comment by LukasCBossert** [comment]
Habe das mit `\AtEveryCite{\ifbool{cbx:kapitaelchen}{\renewcommand*{\mkbibnamelast}[1]{\textsc{#1}}}{}}` eingebaut, sodass man dies steuern kann, ansonsten werden die Autorennamen immer in `\textsc`ausgegeben.

**Comment by moewew** [comment]
Ah ja, natürlich, ich hätte es wohl wieder andersherum gemacht,

```
\DeclareBibliographyOption{kapitaelchen}[true]{%
  \ifstrequal{#1}{true}
    {\AtEveryCite{\renewcommand*{\mkbibnamelast}[1]{\textsc{#1}}}}
    {}}%
```

Damit kann man dann den boolean `cbx:kapitaelchen` einsparen.

**Comment by LukasCBossert** [comment]
Mit 
```
\DeclareBibliographyOption{kapitaelchen}[true]{%
  \ifstrequal{#1}{true}%
    {\AtEveryCite{\renewcommand*{\mkbibnamelast}[1]{\textsc{#1}}}}%
    {}}%
```

funktioniert es nicht?!!?

**Comment by moewew** [comment]
Oh, ja, es muss natürlich

```
\DeclareBibliographyOption{kapitaelchen}[true]{%
  \ifstrequal{#1}{true}%
    {\AtEveryCite{\renewcommand*{\mkbibnamelast}[1]{\textsc{##1}}}}%
    {}}%
```

heißen und Du darfst das Namensformat `cite:author` nicht mehr verwenden. (Ad hoc mit `\DeclareNameAlias{cite:author}{labelname}` und vernünftig, indem Du alle Vorkommen von `cite:author` entfernst.)

**Comment by LukasCBossert** [comment]
ah, den doppelten `#` hätte ich auch sehen können.
Alles erledigt. `cite:author`ist eliminiert.
