### ISSUE TITLE
slash in journal+number+year 

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#40]
Den slash in journal+number+year bekommt man ohne Abfrage etwas idiomatischer mit

\renewbibmacro*{journal+number+year}{%  
  \usebibmacro{journal}%
  \setunit*{\addnbspace}%   
  \printfield{volume}%                          
  \setunit{\addslash}%
  \printfield{number}%      
  \newunit%       
  \printfield{year}%     
}%
es wäre eine nette Möglichkeit, dort statt \addslash so etwas wie \volnumdelim zu schreiben und das den Nutzer selbst ändern zu lassen. Das ist ein häufiger Wunsch bei Nutzern.

**Comment by LukasCBossert** [comment]
slash verbessert. aber  \volnumdelim verstehe ich nicht.

**Comment by moewew** [comment]
Mit `\volnumdelim` schwebte mir in etwa

```
\newcommand*{\volnumdelim}{\addslash}
\newbibmacro{journal+number+year}{%
  \usebibmacro{journal}%
  \setunit{\addnbspace}%
  \printfield{volume}%
  \setunit{\volnumdelim}% 
  \printfield{number}% 
  \newunit%
  \printfield{year}%
}%
```

vor, dann kann ein Nutzer mit nur einer Zeile (`\renewcommand*{\volnumdelim}{\dddot}` zum Beispiel) nämlich den Trenner zwischen `volume` und `number` ändern. Man kann natprlich auch gleich noch über `\jourvoldelim` nachdenken

```
\newcommand*{\volnumdelim}{\addslash}
\newcommand*{\jourvoldelim}{\addnbspace}
\newbibmacro{journal+number+year}{%
  \usebibmacro{journal}%
  \setunit{\jourvoldelim}%
  \printfield{volume}%
  \setunit{\volnumdelim}% 
  \printfield{number}% 
  \newunit%
  \printfield{year}%
}%
```

**Comment by LukasCBossert** [comment]
wunderbar! übernommen!
