### ISSUE TITLE
lbx-Datei ausgelagert

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#45]
Weiter kann darüber nachgedacht werden, die große Datei archaeologie.bbx etwas zu entlasten. Es sollte möglich sein, die dai-abkuerzungen.bib direkt als eigene Datei mitzuliefern anstatt sie mit filecontents zu erstellen. Außerdem kann es sinnvoll sein, die Sprachfeatures in \DefineBibliographyStrings in eigene .lbx-Dateien auszulagern.

**Comment by LukasCBossert** [comment]
lbx wurde für "ngerman" und "english" ausgelagert. Problem ist noch die Einbindung der .lbx-Dateien
dai-abkuerzungen.bib habe ich nicht geschafft.

**Comment by moewew** [comment]
Die `.lbx` werden mit `\DeclareLanguageMapping{ngerman}{archaeologie}` und `\DeclareLanguageMapping{english}{archaeologie_english}` eingebunden. Das kann soweit ich weiß auch in der `.bbx`-Datei erfolgen. (Die Stilfamilie `biblatex-philsophy` macht es so.)

**Comment by LukasCBossert** [comment]
so habe ich es in der bbx stehen  - aber es funktioniert nur, wenn die lbx-dateien auf der ebene der .tex-Datei liegt!?

**Comment by moewew** [comment]
Eigentlich sollte das auch so funktionieren, wenn die `.lbx` nur irgendwo in den von LaTeX durchsuchten Verzeichnissen liegt. Unter Umständen musst Du die Datei erst in der file name database anmelden. Bei MikTeX würde man dazu die FNDB erneuern (in den Settings), bei TeX Live wohl mit der Kommadozeile `initexmf --update-fndb` (bzw. `initexmf --update-fndb --admin`).

**Comment by LukasCBossert** [comment]
mit TeX Live bekomme ich nur die Fehlermeldung `-bash: --update-fndb: command not found`wenn ich im Terminal eintippe: `initexmf --update-fndb --admin`

**Comment by moewew** [comment]
Oh, es kann sein, dass `initexmf` auch ein MikTeX-Befehl ist, ich habe kein TeX Live und das nur schnell gegoogelt und mich wohl verlesen. Anscheindend (https://www.tug.org/fonts/fontinstall.html#fndb) braucht man bei TeX Live `mktexlsr` oder `texhash`.

Diese Befehl muss nur einmal ausgeführt werden, um die neuen Dateien bei TeX "anzumelden", dazu muss die Datei aber in einem von LaTeX durchsuchten Pfadbereich liegen. Insbesondere ist es so, dass Nutzer, die Pakete von CTAN mit dem Installationstool ihrer Distribution installieren, das nicht selbst machen müssen, das geschieht automatisch.

Es ist genau dasselbe mit der ausgelagerten `.bib`-Datei (https://github.com/giovannotti/biblatex-archaeologie/issues/50), wenn `mktexlsr` oder `texhash` gelaufen sind, sollte sie für TeX zur Verfügung stehen (das kann man mit `kpsewhich dai-abkuerzungen.bib` dann testen, wenn es geklappt hat, wird der Pfad, wo die Datei liegt ausgegeben, ausgegeben).

**Comment by LukasCBossert** [comment]
Habe `mktexlsr` und `texhash`durchlaufen lassen (über `sudo mktexlsr` und `sudo texhash`).
Das hat funktioniert. aber bekomme keine Information wenn ich `kpsewhich dai-abkuerzungen.bib` eintippe.

**Comment by moewew** [comment]
Mhhh, liegt die `dai-abkuerzungen.bib` denn in einem von LaTeX durchsuchten Ordner? Hat es für die `.lbx`en funktioniert?

**Comment by LukasCBossert** [comment]
funktioniert nun prima! die beiden `.lbx`und die `.bib`-Datei werden gefunden. Ich schließe das Issue
