### ISSUE TITLE
Option jahrinklammern

### ISSUE THREAD

**Issue by moewew** [giovannotti/biblatex-archaeologie#46]
Die Option `jahrinklammern` kann mit etwas weniger If-Abfragen wie folgt implementiert werden

```
\DeclareFieldFormat{citeyear}{#1}
\DeclareBibliographyOption{jahrinklammern}[true]{%
  \ifstrequal{#1}{true}
    {\DeclareFieldFormat{citeyear}{\mkbibparens{##1}}}
    {\DeclareFieldFormat{citeyear}{##1}}}


\renewbibmacro*{cite:year}{%			
  \iffieldundef{labelyear}
    {}%
    {\printtext[bibhyperref]{\printtext[citeyear]{\printfield{labelyear}\printfield{extrayear}}}}}

\renewbibmacro*{shorthand+year}{%
  \printtext[brackets]{%
    \printfield{shorthand}%
    \setunit{\addspace}%
    \printtext[citeyear]{\printfield{labelyear}\printfield{extrayear}}}}
```

So sparen wir die Doppelungen und erlauben sogar dem Nutzer mit `\DeclareFieldFormat{citeyear}{#1}` ganz ausgefallene Dinge zu tun.

**Comment by giovannotti** [comment]
Oho, das ist aber eine sehr elegante Lösung, Gefällt mir außerordentlich!
Schon umgesetzt.

**Comment by moewew** [comment]
Es ist nur eine ganz kleine Kleinigkeit, aber ich hätte oben statt `\renewbibmacro*` natürlich nur `\newbibmacro*` schreiben sollen. Mit `\renewbibmacro*` erzeugt der Code eine Warnung, dass, da das Makro undefiniert ist, stattdessen `\newbibmacro*` genutzt wird.

**Comment by giovannotti** [comment]
Natürlich, habe es geändert.
