### ISSUE TITLE
option antik bei book und incollection unterschiedlich

### ISSUE THREAD

**Issue by giovannotti** [giovannotti/biblatex-archaeologie#47]
betrifft Translator und Editor

@book{Caes_Gall,
	Author = {Iulius Caesar, Caius},
	Date = {1980},
	Edition = {6},
	**Editor = {Georg Dorminger},**
	Keywords = {Quelle},
	Location = {M{\"u}nchen},
	Namea = {Caesar},
	Options = {antik},
	Origdate = {1962},
	Origlanguage = {latin},
	Origtitle = {Bellum Gallicum},
	Owner = {Lukas C. Bossert},
	Publisher = {Heimeran},
	Shorthand = {Caes. Gall.},
	Timestamp = {2015-43-24},
	Title = {Der Gallische Krieg}}

ergibt

C. Iulius Caesar, Der Gallische Krieg, Orig.titel: Bellum Gallicum, **translated** aus dem Lateinischen 6(München 1962; Nachdr. München 1980)

@incollection{Cic_Arch,
	Author = {Tullius Cicero, Marcus},
	Date = {1993},
	**Editor = {Fuhrmann, Manfred},**
	Keywords = {Quelle},
	Location = {M{\"u}nchen},
	Maintitle = {Die politischen Reden},
	Options = {antik},
	Origlanguage = {latin},
	Origtitel = {pro Archia poeta},
	Owner = {Lukas C. Bossert},
	Pages = {6--37},
	Publisher = {Artemis \& Winkler},
	Series = {Sammlung Tusculum},
	Shorthand = {Cic. Arch.},
	Timestamp = {2015-05-30},
	Title = {Rede f{\"{u}}r den Dichter A.\ Licinius Archias},
	**Translator = {Fuhrmann, Manfred},**
	Usera = {Cicero},
	Volume = {2}}

dagegen

M. Tullius Cicero, Rede für den Dichter A. Licinius Archias aus dem Lateini- schen übers. v. M. Fuhrmann, in: M. Fuhrmann (Hrsg.), Die politischen Reden 2, Sammlung Tusculum (München 1993) 6–37

**Comment by LukasCBossert** [comment]
ich denke aber, dass es nicht an @book oder @incollection liegt, sondern daran, dass bei dem @book-eintrag kein "translator" angegeben ist. scheint mir also an sich kein programmierfehler zu sein, sondern dann in dem Fall ein vergessener Eintrag.

**Comment by giovannotti** [comment]
So kann man es auch sehen, ich dachte mehr daran, dass der Editor dann im oberen Fall des @books gar keine Verwendung hat. Am Allergeilsten wäre natürlich bei @book:

- Eintrag mit editor und translator -> "herausgegeben und übersetzt von"
- Eintrag mit translator -> "übersetzt von" 
- Eintrag mit editor -> "herausgegeben von"

Bei @incollection macht es ja dann so Sinn, wie es jetzt ist.

**Comment by LukasCBossert** [comment]
sehr gute Idee.
Das könnte man mit dem Bibstring
byeditortr       = {{herausgegeben und \lbx@lfromlang \"ubersetzt von}%
                      {hrsg\adddotspace und \lbx@sfromlang \"ubers\adddot\ v\adddot}},
(geliehen bei biblatex-dw)
realisieren.

**Comment by moewew** [comment]
Soweit ich weiß, kann der Standard von `biblatex` das schon (z.B. zu sehen im Eintrag `averroes/bland`), das Zaubermakro heißt `byeditor+others`.

**Comment by LukasCBossert** [comment]
`bibaltex`-Handbuch S. 213. Sehr interessant! Ich klemme mich dahinter.

**Comment by LukasCBossert** [comment]
Mit dem letzten Commit umgesetzt.

**Comment by moewew** [comment]
Ich denke, Du kannst Dein eigenes Makro `translation` einfach durch `byeditor+others` ersetzen, letzteres macht was Du machst auch intern.

**Comment by LukasCBossert** [comment]
Mit dem Makro `translation`soll umgesetzt werden, dass bei den Einträgen `antik`immer die Übersetzungsangaben kommt, bei den anderen nur optional.

**Comment by moewew** [comment]
Mhh, ist es gerade nicht immer Optional? Wenn ihr keine `translator` wollt, könnt ihr sie ja einfach mit 
`\AtEveryBibitem{\ifbool{bbx:uebersetzung}{}{\clearname{translator}\clearfield{origtitle}}}` loswerden

**Comment by moewew** [comment]
Mit
```
\AtEveryBibitem{%
  \ifboolexpr{bool {bbx:uebersetzung} or bool {cbx:antik} or bool {cbx:frgantik}}
    {}
    {\clearname{translator}%
     \clearfield{origtitle}}}

\DeclareFieldFormat{origtitle}{\mkbibemph{#1}}

\newbibmacro{translation}{%
  \printfield{origtitle}%
  \setunit{\addcomma\space}%
  \usebibmacro{byeditor+others}}
```

bekommen wir auch, was ihr wollt. (Man müsste jetzt noch den `@article`-Treiber anpassen.)

**Comment by LukasCBossert** [comment]
erledigt.
