### ISSUE TITLE
\ifnameundef statt cbx:unbekannt?

### ISSUE THREAD

**Issue by giovannotti** [giovannotti/biblatex-archaeologie#48]
Der Nachteil von der cbx-Option ist, dass man sie in den Einträgen der Bibfile nicht vergessen darf. Falls sie vergessen wird, gibt es keine default-Lösung: es steht dann einfach nur eine Jahreszahl. Alternativ könnte man in der Bibliographie einfach \ifnameundef schreiben und als TRUE-Ergebnis \usebibmacro{shorthand+year} verwenden.
An den beiden Stellen, wo die Option in Bibliography-Driver Verwendung findet, kann man ähnlich agieren.

Oder gibt es einen anderen Grund für diese cbx-Option?

**Comment by LukasCBossert** [comment]
klingt nach einer guten Lösung. Setzt du das um?

**Comment by giovannotti** [comment]
erledigt, allerdings gab es Konflikte, musste mergen. Jetzt müssen wir die Verwendung von \newunit nach Autor/Editor überprüfen, da fehlende Daten nun oft einen freistehenden \newunitpunct (Komma) erzeugen.

**Comment by moewew** [comment]
In den meisten Fällen könnte das `\ifbool{cbx:unbekannt}` wohl einfach durch `\ifnameundef{labelname}` ausgetauscht werden. Die Frage ist, ob ihr die `nurshorthand`-Geschichte braucht, wenn ihr bei unbekannten Werken von `shorthand` einfach auf das dafür gedachte `label` ausweicht. Hier tritt das `label` an die Stelle des fehlenden Namen. Sonst ist für Werke mit `shorthand` nämlich das Verhalten von `nurshorthand` die Norm.

Also im Beispiel aus der Doku
```
@Article{Cosa_1949,
Title = {Cosa},
Journaltitle = ClJ-lang,
Shortjournal = ClJ-kurz,
Pages = {141--149},
Volume = {45},
Year = {1949},
Number = {1},
label = {Cosa},
Subtitle = {Republican Colony in Etruria},
}
```
(`label = {Cosa},` statt `shorthand = {Cosa},`)


Vergleiche im Standard
```
\documentclass[a4paper,ngerman]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}
\usepackage[style=authoryear]{biblatex}

\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
@Article{Cosa_1949,
Title = {Cosa},
Journaltitle = {Cosa als label},
Pages = {141--149},
Volume = {45},
Year = {1949},
Number = {1},
label = {Cosa},
}
@Article{Cosa_1950,
Title = {Cosa},
Journaltitle = {Cosa als shorthand},
Pages = {142--150},
Volume = {46},
Year = {1950},
Number = {2},
shorthand = {Cosa},
}
\end{filecontents*}

\addbibresource{\jobname.bib}


\begin{document}
\cite{Cosa_1949} aber \cite{Cosa_1950}%

\printbibliography
\end{document}
```

**Comment by giovannotti** [comment]
Finde ich gut. Lukas? @LukasCBossert

**Comment by LukasCBossert** [comment]
@giovannotti ja, eine gute Umsetzung für die namenlosen Einträge. Gekauft.

**Comment by LukasCBossert** [comment]
Ich habe es ausprobiert mit:

```
@Article{Cosa_1949,
Title = {Cosa},
Journaltitle = ClJ-lang,
Shortjournal = ClJ-kurz,
Pages = {141--149},
Volume = {45},
Year = {1949},
Number = {1},
label = {Cosa},
Subtitle = {Republican Colony in Etruria},
}
```

Aber das Label erscheint nicht, sondern nut `[1949]`.

Ein Problem sehe ich noch bei den Reihen (bspw. 
```
@Book{CIL,
  Title                    = CIL-lang,
  Keywords                 = {Sigel},
  Options                  = {nurshorthand},
  Shorthand                = CIL-kurz
}
```
), da die ohne Jahr angezeigt werden sollen und momentan stattdessen ein `o.D.`erscheint.

**Comment by moewew** [comment]
Ja, das liegt daran, dass euer `cite` Makro das `label` nicht benutzt und für `shorthand`s ist. Du kannst Dir ja mal `authoryear.cbx` ansehen, was da passiert.

**Comment by moewew** [comment]
Was Du mit dem `@Book{CIL,` möchtest, kann man bestimmt irgendwie anders erreichen. Es gibt z.B. http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/examples/92-bibliographylists.tex und http://tex.stackexchange.com/q/29122/35864

**Comment by LukasCBossert** [comment]
Ich habe mich gerade frecherweise mit diesem Issue beschäftigt (sorry @giovannotti) und dabei ein paar Dinge umgestellt.

Die Cosa-Sache funktioniert nun nur mit `label={Cosa}`ohne die `options={unbekannt}`

Bei der CIL-Sache würde es auch funktionieren, da der entscheidende Unterschied die Ausgabe eines Kommas nach dem Label ist. Es würde funktionieren mit:

```
\newbibmacro*{cite:year}{%            
  \iffieldundef{labelyear}
    {}%
    {{\printtext[citeyear]{\printfield{labelyear}\printfield{extrayear}}}}}

\newbibmacro*{cite:label}{%
  \iffieldundef{label}
    {\printfield[citetitle]{labeltitle}}
    {\printfield{label}}}

\newbibmacro*{cite:label+year}{%
		\usebibmacro{cite:label}%
         \ifnameundef{labelname}{}{\addspace%
         \usebibmacro{cite:year}%
         }%
         }
```

Allerdings habe ich mir überlegt, dass es vielleicht besser ist die Corpora der Altertumswissenschaften auch explizit als solche zu kennzeichnen. Dafür habe ich die Option `nurshorthand` in `corpus`umbenannt, da `nurshorthand`ohnehin auf die Corpora zutraf.
Daher sieht das `bibmacro`nun so aus:

```
\newbibmacro*{cite:label+year}{%
		\usebibmacro{cite:label}%
         \ifbool{cbx:corpus}{}{\addspace%
         \usebibmacro{cite:year}%
         }%
         }
```

Es funktioniert und ich habe bisher keinen Fehler entdeckt.

**Comment by moewew** [comment]
Mir scheint es fast so, als sei `@book` für 
```
@Book{CIL,
  Title                    = CIL-lang,
  Keywords                 = {Sigel},
  Options                  = {nurshorthand},
  Shorthand                = CIL-kurz
}
```
der falsche Typ. Vielleicht erstellt ihr dafür lieber einen eigenen Typen, als `@book` mit einer Option zu überladen. Unter Umständen kann das sogar schon mit biblists erreicht werden (wir haben das in https://github.com/giovannotti/biblatex-archaeologie/issues/61 angerissen)

**Comment by LukasCBossert** [comment]
Da ist mir noch unklar, wie es konkret für den "CIL"-Eintrag aussehen kann.
```
@String {CIL= {Corpus inscriptorum latinorum}}
```
oder eher
```
@xdata{CIL,
  shorttitle = {CIL},
  title  = {Corpus inscriptorum latinorum},
}
```

Aber wie kann man auf diese Einträge dann konkret zurückgreifen und sie im Fließtext zitieren?

**Comment by moewew** [comment]
Ah, ich dachte erst, das sein nur zu Auflösen von Abkürzungen und würde im Text gar nicht zitiert.

Ich könntet z.B. einen eigene Typ für corpora/Datenbanken erstellen. Weder mit `@xdata` noch mit `@string`, sondern einen eigen Typen, [ein kompliziertes Beispiel dazu ist hier](http://tex.stackexchange.com/q/175776/35864), [ein etwas weniger aufwändiges hier](http://tex.stackexchange.com/q/17627/35864). 

Aber vielleicht machen wir es hier gerade viel zu kompliziert.

Von der grundsätzlichen Idee von `label` und `shorthand` sehe ich es so, dass `label` einen fehlenden Namen ersetzten soll und mit dem Jahr auftritt, `shorthand` hingegen ersetzt die gesamte Kennzeichnung für das Werk (es wird weder Jahr noch Titel zusätzlich angezeigt).

Wenn ich `label = {Cosa}, year = {1949}, title= {Blah}` habe, erwarte ich "Cosa 1949" in der Ausgabe (`label` ersetzt nur den fehlenden Autor, das Jahr bleibt); bei `shorthand = {CIL}, year = {1920}, title= {Blah}, author = {Anne Uthor}` erwarte ich nur "CIL" (das `shorthand` setzt sich über alles hinweg).

Ich würde also bei dem `cosa`-Eintrag das `label` verwenden und bei `CIL` das `shorthand`. Dann muss alles nur in etwa wie bei `authoyrear.cbx` implementiert werden, und alles läuft wie es soll.

**Comment by LukasCBossert** [comment]
Prima. Dann haben wir `cbx:unbekannt` eliminiert und können das mit `label={}`kompensieren. 
der `CIL`-Eintrag habe ich wieder auf `shorthand`zurückgesetzt und für die Bibliographie etwas umgestellt, dass zuerst geschaut wird ob etwas `antik`, `frgantik`, oder `corpus` ist und dann erst das `bibmacro{label+year}`durchlaufen lassen. 
So wie ich das sehe, funktioniert alles.

Wenn aus Programmiersicht nichts dagegen spricht, würde ich dafür plädieren den Eintrag für Corpora mit `book`beizubehalten, da es mir einfacher und intuitiver scheint. Was meinst du, @giovannotti ?

**Comment by moewew** [comment]
Ich denke es wäre einfacher, anstatt auf `antik`, `frgantik` oder `corpus` einfach auf `\iffieldundef{shorthand}` zu testen.

```
\newcommand*{\labelyeardelim}{\addspace}

\renewbibmacro*{cite}{%
  \printtext[bibhyperref]{%
    \ifbool{cbx:lexikon}
      {\usebibmacro{cite:lexikon}}
      {\iffieldundef{shorthand}
        {\ifnameundef{labelname}%
           {\usebibmacro{cite:label}
            \setunit{\labelyeardelim}}%
           {\printnames{labelname}%
            \setunit{\nameyeardelim}}%
         \usebibmacro{cite:year}}%
        {\printfield{shorthand}}}}}%
```

Dann brauchen wir `cite:label+year` nicht mehr. (Außerdem ist es besser `\printtex[bibhyperref]{foo}` statt `\bibhyperref{foo}` zu nutzen, siehe 4.11.7.2 Common Mistakes in der `biblatex`-Doku)

**Comment by LukasCBossert** [comment]
stimmt. das spart einige Zeilen unnötige Programmierung.

**Comment by moewew** [comment]
Nun da das `cite`-Makro so schön aufgeräumt ist, könnt ihr `labelwidthbib` viel kürzer bekommen

```
\newbibmacro{labelwidthbib}{%
  \csuse{blx@hook@cite}%
  \csuse{blx@hook@citekey}%
  \defcounter{maxnames}{\blx@maxcitenames}%
  \usebibmacro{cite}}
```

Ich glaube übrigens auch, dass `cite:title` etwas schneller geht

```
\newbibmacro*{cite:title}{\printfield[citetitle]{labeltitle}}%  
```

Das Makro `cite:label+year` kann auch weg.

Bei `cite:lexikon` und `\DeclareCiteCommand{\citetitle}` sind noch ein paar Dinge etwas unüblich gelöst. Dinge wie `\addspace` würde ich immer in `\setunit` setzten. `\mkbibemph` sollte außerhalb von `\DeclareFieldFormat` eigentlich immer durch `\printtext[emph]` ersetzt werden (ebenso `\mkbibparens` durch `\printtext[parens]`, da sieht man sogar einen Unterschied), vielleicht lässt sich das hier aber auch anders lösen (z.B. durch `\DeclareFieldFormat`)

**Comment by LukasCBossert** [comment]
Kann es sein, dass das Makro
```
\newbibmacro{labelwidthbib}{%
  \csuse{blx@hook@cite}%
  \csuse{blx@hook@citekey}%
  \defcounter{maxnames}{\blx@maxcitenames}%
  \usebibmacro{cite}}
```
Dazu führt, dass die Labels in der Bibliographie auch noch mit einem `bibhyperref`"hinterlegt" sind. Wenn ich auf diese klicke verweisen sie auf sich selbst. Wie kann man das abschalten? Gibt es ein "un-"`bibhyperref`? Ansonsten funktioniert die verkürzte Version.

**Comment by giovannotti** [comment]
Bin mit allem d'accorr, je schlanker, desto besser. Dann ist `shorthand` die Allzweckwaffe. @LukasCBossert, mach du fertig, denn du bist jetzt mehr drin in der Angelegenheit.

**Comment by LukasCBossert** [comment]
Ich habe nun ein kleines "Workaround" gebastelt:

```
\newbibmacro{labelwidthbib}{%
  \csuse{blx@hook@cite}%
  \csuse{blx@hook@citekey}%
  \defcounter{maxnames}{\blx@maxcitenames}%
  \usebibmacro{cite:bib}}

\newbibmacro*{cite:bib}{%
    \ifbool{cbx:lexikon}
      {\usebibmacro{cite:lexikon}}
      {\iffieldundef{shorthand}
        {\ifnameundef{labelname}%
           {\usebibmacro{cite:label}
            \setunit{\labelyeardelim}}%
           {\printnames{labelname}%
            \setunit{\nameyeardelim}}%
         \usebibmacro{cite:year}}%
        {\printfield{shorthand}}}}%
```
Es funktioniert, könnte aber vielleicht schlanker gemacht werden. Das entscheidende ist, dass `  \printtext[bibhyperref]` bei `\renewbibmacro*{cite}` rausfliegt.

**Comment by LukasCBossert** [comment]
Kommando zurück - es funktioniert auf einmal doch nicht mehr.

**Comment by moewew** [comment]
Oh, das mit dem Link hatte ich übersehen. Man kann das so verhindern, wie Du es getan hast, aber geht es mit 

```
\newbibmacro{labelwidthbib}{%
  \csuse{blx@hook@cite}%
  \csuse{blx@hook@citekey}%
  \defcounter{maxnames}{\blx@maxcitenames}%
  \usebibmacro{cite:bib}}

````

in der `.bbx` und dann in der `.cbx`

```
\newbibmacro*{cite:nolink}{%
    \ifbool{cbx:lexikon}
      {\usebibmacro{cite:lexikon}}
      {\iffieldundef{shorthand}
        {\ifnameundef{labelname}%
           {\usebibmacro{cite:label}
            \setunit{\labelyeardelim}}%
           {\printnames{labelname}%
            \setunit{\nameyeardelim}}%
         \usebibmacro{cite:year}}%
        {\printfield{shorthand}}}}%

\newbibmacro{cite}{\printtext[bibhyperref]{\usebibmacro{cite:nolink}}}
```

nicht etwas kürzer

Oder Du lässt den Link in `cite` ganz weg und fügst ihn nur in

```
\DeclareCiteCommand{\cite}%              
  {\usebibmacro{prenote}}%
  {\usebibmacro{citeindex}%
  \printtext[bibhyperref]{\usebibmacro{cite}}}%
  {\multicitedelim}%
  {\ifboolexpr{bool{cbx:lexikon} and bool {bbx:lexika}}{}{\usebibmacro{postnote}}}%
```

hinzu.

Auf diese Weise können unnötige Doppelungen vermieden werden, es wäre sehr ärgerlich, eine wichtige Änderung nur bei einem von den beiden `cite` oder `cite:bib` Makros auszuführen und bei dem anderen zu vergessen.

**Comment by LukasCBossert** [comment]
Ich nehme an, du meinst 
```
\newbibmacro{labelwidthbib}{%
  \csuse{blx@hook@cite}%
  \csuse{blx@hook@citekey}%
  \defcounter{maxnames}{\blx@maxcitenames}%
  \usebibmacro{cite:nolink}} %<---- diese Änderung!
```

**Comment by LukasCBossert** [comment]
Es gibt nur leider nochmals ein Problem, das wegen `cbx:lexikon` besteht.
Mit deiner oben angegebenen Lösung bleibt ein `bibhyperref` für die `cbx:lexikon` bei `bbx:lexika`bestehen.

Daher war ein Lösungsansatz von mir
```
\newbibmacro*{cite}{%
    \ifbool{cbx:lexikon}%
      {\usebibmacro{cite:lexikon}}
      {\printtext[bibhyperref]{\iffieldundef{shorthand}
        {\ifnameundef{labelname}%
           {\usebibmacro{cite:label}
            \setunit{\labelyeardelim}}%
           {\printnames{labelname}%
            \setunit{\nameyeardelim}}%
         \usebibmacro{cite:year}}%
        {\printfield{shorthand}}}}}%
```
Damit soll der `bibhyperref` erst nach der Option `cbx:lexikon` greifen. Komme aber nicht drauf, wie es mit der anderen Lösung verquickt werden kann.

**Comment by moewew** [comment]
Oh ja sicher, das habe ich übersehen.

Eine viel bessere Idee scheint mir, `{cite}` mit allen Links zu definieren und die dann einfach temporär in dem Label-Teil der Bibliographie auszuschalten

```
\newbibmacro{labelwidthbib}{%
  \begingroup
    \DeclareFieldFormat{bibhyperref}{##1}%
    \csuse{blx@hook@cite}%
    \csuse{blx@hook@citekey}%
    \defcounter{maxnames}{\blx@maxcitenames}%
    \usebibmacro{cite}%
  \endgroup}   
```

Vielleicht sollte `cite:lexikon` aber auch noch mal überarbeitet werden. Mir scheint es beispielsweise so, dass die Abfrage `\ifbool{bbx:lexika}` in `cite:lexikon` schon nach `cite` ausgelagert werden könnte, wo man dann statt `\ifbool{cbx:lexikon}` wie so häufig `\ifboolexpr{bool {cbx:lexikon} and bool {bbx:lexika}}` verwendet.

**Comment by LukasCBossert** [comment]
Ich habe jetzt geschrieben:
```
\defbibenvironment{bibliography}
  {\list
     {\usebibmacro{labelwidthbib}}
     {\setlength{\labelwidth}{\shorthandwidth}%
      \setlength{\leftmargin}{\labelwidth}%
      \setlength{\labelsep}{\biblabelsep}%
      \addtolength{\leftmargin}{\labelsep}%
      \setlength{\itemsep}{\bibitemsep}%
      \setlength{\parsep}{\bibparsep}%
      \renewcommand*{\makelabel}[1]{##1\hss}}}
  {\endlist}
  {\ifboolexpr{bool{cbx:lexikon} and bool {bbx:lexika}}{}%
  {\item\usebibmacro{kicklabel}}%
  }

\newbibmacro{labelwidthbib}{%
  \begingroup
    \DeclareFieldFormat{bibhyperref}{##1}%
    \csuse{blx@hook@cite}%
    \csuse{blx@hook@citekey}%
    \defcounter{maxnames}{\blx@maxcitenames}%
    \usebibmacro{cite}%
  \endgroup}   


\newbibmacro*{cite:lexikon}{%
  				\printfield{booktitle}%
  				\setunit{\addspace}%
  				\printfield{volume}%
  				 \setunit{\addspace}%
  				\printfield[parens]{year}%
  				\setunit{\addspace}%
  							\iffieldundef{postnote}{\printfield{pages}}{\printfield{postnote}}%
  				\setunit{\addspace}\printtext{s\adddot\addnbthinspace v\adddot}%
  				\setunit{\addspace}\printfield{title}%
  				\setunit{\addspace}\printtext[parens]{\c@uniquename=1 \printnames{labelname}}%
}


\newbibmacro{cite}{%
    \ifboolexpr{bool{cbx:lexikon} and bool {bbx:lexika}}%
      {\usebibmacro{cite:lexikon}}%
      {\printtext[bibhyperref]{\iffieldundef{shorthand}
        {\ifnameundef{labelname}%
           {\usebibmacro{cite:label}%
            \setunit{\labelyeardelim}}%
           {\printnames{labelname}%
            \setunit{\nameyeardelim}}%
         \usebibmacro{cite:year}}%
        {\printfield{shorthand}}}}%
}
```

Damit ist das Ergebnis wie gewünscht. 
Dennoch gibt es in der `archaeologie.tex` Fehlermeldungen bei mehreren kleinen Beispielbibliographien, die entweder einen Eintrag mit `cbx:lexikon` oder ohne haben (und bei der Beispielbibliographie mit `\cite{Nieddu_1995}` erscheint auch nochmals der Bibliographieeintrag -- in der großen Gesamtbibliographie dann allerdings nicht; wie es gewünscht ist)

**Comment by LukasCBossert** [comment]
Kommando zurück. Es Funktioniert NICHT!

**Comment by moewew** [comment]
Ein Problem scheint zu sein, dass in der Bibliographie bei `@inreference`s nicht unbedingt das auftauchen darf, was zitiert wurde. Oder die `@inreference` selbst gar nicht, sondern stattdessen die zugehörige `@reference`, auch wenn die nicht zitiert wurde.
Das ist natürlich für so kurze Lösungen, wie ich sie bevorzuge, ungünstig. Dann kann es doch besser sein, ein `cite` und ein `cite:bib` zu definieren, die dann jeweils das richtige tun.

**Comment by LukasCBossert** [comment]
```
\newbibmacro{cite:bib}{%
    \ifboolexpr{bool{cbx:lexikon} and bool {bbx:lexika}}%
      {}%
      {\printtext[bibhyperref]{\iffieldundef{shorthand}
        {\ifnameundef{labelname}%
           {\usebibmacro{cite:label}%
            \setunit{\labelyeardelim}}%
           {\printnames{labelname}%
            \setunit{\nameyeardelim}}%
         \usebibmacro{cite:year}}%
        {\printfield{shorthand}}}}%
}
```
Übergeht leider nicht den Eintrag .... Wo habe ich meinen Denkfehler!?

**Comment by moewew** [comment]
Das würde doch nur das Label weglassen, oder nicht? Zur Zeit tut es aber gar nicht, da wir ja `cite` und nicht `cite:bib` aufrufen

```
\newbibmacro{labelwidthbib}{%
  \begingroup
    \DeclareFieldFormat{bibhyperref}{##1}%
    \csuse{blx@hook@cite}%
    \csuse{blx@hook@citekey}%
    \defcounter{maxnames}{\blx@maxcitenames}%
    \usebibmacro{cite}%
  \endgroup} 
```

**Comment by LukasCBossert** [comment]
Ok, also die Label werden schonmal weggelassen. Wenn ich jetzt noch den Eintrag an sich rauswerfen will, dann schaffe ich es nur, wenn ich hier manipuliere:
```
\defbibenvironment{bibliography}
  {\list
     {\usebibmacro{labelwidthbib}}
     {\setlength{\labelwidth}{\shorthandwidth}%
      \setlength{\leftmargin}{\labelwidth}%
      \setlength{\labelsep}{\biblabelsep}%
      \addtolength{\leftmargin}{\labelsep}%
      \setlength{\itemsep}{\bibitemsep}%
      \setlength{\parsep}{\bibparsep}%
      \renewcommand*{\makelabel}[1]{##1\hss}}}
  {\endlist}
  {\item\usebibmacro{kicklabel}} %<--- Hier
```
Was aber a) nicht schön ist, und b) zu Fehlermeldungen führt. 
Wie funktioniert das mit dem `bibcheck` bzw. `defbibfilter`? Mir wurde nicht klar, welches sich eigenen würde.
Wenn ich das richtig sehe, müsste der Endnutzer ebenfalls noch einbauen, dass die Bibliographie den Filter dann berücksichtigt?

**Comment by LukasCBossert** [comment]
Bei einem `bibcheck` müsste man ja sagen, dass auf den `related`-verknüpften Eintrag zugegriffen wird und dann wie bei 
```
\defbibcheck{shortjournal}{%
    \iffieldundef{shortjournal}{\skipentry}{}%
    \iffieldundef{journaltitle}{\skipentry}{%
        \ifcsdef{\strfield{journaltitle}}{\skipentry}{\savefieldcs{journaltitle}{\strfield{journaltitle}}}%   
            }}%  
```
Dass der `related`-Eintrag nur einmal erscheinen soll.

Irgendwas in die Richtung von:
```
\defbibcheck{inreference}{%
\ifentrytype{inreference}{%
    \iffieldundef{booktitle}{\skipentry}{%
        \ifcsdef{\usebibmacro*{related:default}}}%   
            }
{}}%  


```

**Comment by moewew** [comment]
Fehlermeldungen bekomme ich gerade nicht (ich kann mir aber vorstellen, das es Situationen gibt, in denen das ungünstig ist), aber schön finde ich es wirklich nicht.

Leider kann man weder mit `\defbibfilter` noch mit  `\defbibcheck` auf `cbx:lexikon` zugreifen. Außerdem hast Du Recht, der filter oder check müsste in der Bibliographie selbst ausgewählt werden.

Wenn allerdings `cbx:lexikon` eh obsolet wird, sollte es wieder Möglichkeiten geben. Zur Zeit würde

```
\DeclareEntryOption{lexikon}[true]{%
  \csuse{bool#1}{cbx:lexikon}%
  \ifbool{bbx:lexika}{\settoggle{blx@skipbib}{#1}}}%
```
es wohl tun.

**Comment by LukasCBossert** [comment]
Das funktioniert ja wirklich prima!
Bis klar ist, ob `cbx:lexikon` notwendig ist, kann man mit deiner Lösung sehr gut arbeiten.

Die Fehlermeldungen bekam ich mit der `archaeologie.tex`-Datei, wo mehrere kleine Bibliographien erzeugt werden.

**Comment by LukasCBossert** [comment]
Wenn ich mich jetzt nicht irre, dann bedarf es jetzt gar nicht mehr eines `bibmacro{cite:bib}`, dann die Labels in der Bibliographie sind jetzt auch ohne `bibhyperref` (Warum das so ist, ist mir ein wenig unklar...)

**Comment by LukasCBossert** [comment]
Mit dem letzten Update von `biblatex` funktioniert die Ausgabe der Bibliographie zwar noch, aber nicht mehr wie vor zuvor, als die längste Länge einer `shorthand` den Abstand zwischen Label und Bibliographieeintrag bestimmt hat. Stattdessen wird auf den Abstand keine Rücksicht mehr genommen. Leider kann ich den Fehler, bzw. den Unterschied zur bisherigen Version von `biblatex` nicht erkennen, sodass ich auf Hilfe (@moewew) hoffe..... Dafür wurde ein neues issue angelegt: #79
