### ISSUE TITLE
Angabe von u.a. bei mehr als drei Autoren

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#5]
Da muss noch etwas getan werden, denn die DAI-Vorgaben werden noch nicht umgesetzt.
Bei vier oder mehr Autoren wird nur der erste ohne "u. a." genannt, zudem wird dann in der Bibliographie auch nur der erste angegeben und alle weiteren unterschlagen.

**Comment by giovannotti** [comment]
Schau es dir an. Wenn nach deiner Meinung gefixt, bitte Issue schließen.

**Comment by LukasCBossert** [comment]
funktioniert. allerdings noch nicht für \citeauthor - da wird nur der erste Autor/Editor OHNE u.a. angegeben

**Comment by giovannotti** [comment]
Wie hättest du es denn gerne:
Möglichkeiten für Alfoeldy_2003:
- Alföldy u. a.
- Alföldy, Abascal, Cebrián und Bossert
- etc.

oder nur bis 3 Autoren, also:
- Bacchetta, Crosetto und Gambari (bacchetta_2011)
- aber: Alföldy u. a. (alfoeldi_2003)

**Comment by LukasCBossert** [comment]
du meinst jetzt für \citeauthor{}?!
Ich fände es gut, wenn es wie für die Bibliographie gehandhabt wird. Also standard „maxnames=3“ (= DAI-Standard), sodass, wenn vier Autoren, nur der erste und „u.a.“ aufgeführt wird.
Demnach würde ich die zweite Variante bevorzugen:
Bacchetta, Crosetto und Gambari (bacchetta_2011)
aber: Alföldy u. a. (alfoeldi_2003)
oder!?

Am 29.06.2015 um 16:39 schrieb Johannes <notifications@github.com>:

Wie hättest du es denn gerne:
Möglichkeiten für Alfoeldy_2003:

Alföldy u. a.
Alföldy, Abascal, Cebrián und Bossert
etc.
oder nur bis 3 Autoren, also:

Bacchetta, Crosetto und Gambari (bacchetta_2011)
aber: Alföldy u. a. (alfoeldi_2003)

**Comment by giovannotti** [comment]
Ok. Ich habe noch ein Problem mit den vielen Namensbools. Wir haben:
- nurinit für den abgekürzten Vornamen in der Bibliographie
- mitvn für den Vornamen im Kurzzitat
- citeinit für den abgekürzten Vornamen im Kurzzitat
- nurnachname für reine Nachnamen im Fließtextzitat
- vollername für ganzen Namen im Fließtextzitat
- und sonst im Fließtextzitat abgekürzter Vorname und Nachname

Ich fürchte, das ist und wird unübersichtlich. Die Frage ist, ob und wie man etwas vereinheitlichen kann.

**Comment by LukasCBossert** [comment]
ja, ich finde, das wirklich überarbeiten
nurinit für den abgekürzten Vornamen in der Bibliographie
das ist ohnehin eigentlich standard - > ist aber noch nicht umgesetzt?!!!
mitvn für den Vornamen im Kurzzitat
das kann m.E. raus - ich habe kein Interesse in der Fußnote für die Zitation den vollen Vornamen auszuschreiben.
citeinit für den abgekürzten Vornamen im Kurzzitat
wenn man diese Option drin hat, dann muss sich ja auch das Label für die Bibliographie verändern. Kann m.E. auch rausfliegen.
nurnachname für reine Nachnamen im Fließtextzitat
würde ich von der Option her lassen, kann man aber ggf. „besser coden“ 
vollername für ganzen Namen im Fließtextzitat
würde ich von der Option her lassen, kann man aber ggf. „besser coden“ 
und sonst im Fließtextzitat abgekürzter Vorname und Nachname (initialnachname)
das ist ja standard für \citeauthor , aber ggf. ebenso nicht gut gecodet. 


ergo:

für die Präambel-Optionen bleiben nur „nurnachname“ und „vollername“;
- nurinit bleibt, wird aber als standard für Bibliographie gesetzt
- initialnachname bleibt standard und damit auch im hintergrund.

wie findest du das?

**Comment by giovannotti** [comment]
finde ich gut. Nur brauchen wir dann nicht beides (nurnachname und vollername). Weil wenn vollername = false, dann ist automatisch nur Nachname.
Ich würde also sagen:
- vollername = true/false für \citeauthor
- nurinit wird global verwendet, d.h. wenn nurinit = true (standard), dann werden sowohl die Vornamen in der Bibliographie wie auch \citeauthor im Fließtext ausgeschrieben (oder findest du die Koppelung blöd?)
- es fliegen raus: mitvn, citeinit

Habe ich was vergessen?
Ich würde mich dann daran setzen, das umzusetzen und den Code zu verschlanken.

**Comment by LukasCBossert** [comment]
Beim ersten Punkt würde ich dir widersprechen.
Momentan sind es für \citeauthor drei Möglichkeiten:
1) Wenn „nurnachname“ und „vollername“ = false, dann „initialnachname“ (standard)
2) Wenn „nurnachname“ = true, dann ist (automatisch) „vollername“ = false
3) wenn „vollername“ = true, dann ist (automatisch) „nurnachname“ = false

Daher scheint es mir, dass die Standard-Variante („intialnachname“) nicht mehr zum tragen kommt, wenn man nur noch die Option „vollername“ =true/false hat. Oder ist mein logisches Denken hier falsch?

die Frage bei „nurinit“ ist, ob man dies dann noch als „Option“ braucht, wenn es ohnehin global wird (wenn du es so gemeint hast, dass es als Option drin bleibt, aber standardmäßig aktiviert wird). Daher braucht man „nurinit“ als Option gar nicht. 

——— OK, JETZT habe ich kapiert, wie du es gemeint hast (wollte nur nicht die so mühsam getippten Zeilen oben löschen):

hm, ich bin mir unschlüssig, was ich schlüssig finde. 
Bisher fand ich die Möglichkeit Bibliographie und \citeauthor getrennt voneinander zu bestimmen ganz gut. 
Dann kann man dennoch DAI-treu in der Bibliographie bleiben und trotzdem die Namen voll ausgeschrieben im Fließtext.
(Daher würde ich es doch wie bisher für diese Option lassen, ok?)




Am 29.06.2015 um 17:37 schrieb Johannes <notifications@github.com>:

finde ich gut. Nur brauchen wir dann nicht beides (nurnachname und vollername). Weil wenn vollername = false, dann ist automatisch nur Nachname.
Ich würde also sagen:

vollername = true/false für \citeauthor
nurinit wird global verwendet, d.h. wenn nurinit = true (standard), dann werden sowohl die Vornamen in der Bibliographie wie auch \citeauthor im Fließtext ausgeschrieben (oder findest du die Koppelung blöd?)
es fliegen raus: mitvn, citeinit
Habe ich was vergessen?
Ich würde mich dann daran setzen, das umzusetzen und den Code zu verschlanken.

**Comment by giovannotti** [comment]
Ok :+1:

**Comment by giovannotti** [comment]
Da ich heute aufhöre und morgen wenig Zeit habe, wirds ein wenig dauern.
Also falls du wegen einer anderen Issue vorhast, in \DeclareCiteCommand{\citeauthor} und \newbibmacro*{cite:name} herumzustochern… tu's nicht :-) Sonst müssen wir manuell mergen ;-)

Ich kümmer mich dann auch gleich um Issue #10. Das gehört ja da mit rein.

**Comment by LukasCBossert** [comment]
ok - ich werde davon die Finger lassen.
Bibliographiedarstellung ist gelöst.
Mache aber noch Feintuning, sodass es keine neue für die Shorthands gibt.


Am 29.06.2015 um 18:11 schrieb Johannes <notifications@github.com>:

Da ich heute aufhöre und morgen wenig Zeit habe, wirds ein wenig dauern.
Also falls du wegen einer anderen Issue vorhast, in \DeclareCiteCommand{\citeauthor} und \newbibmacro*{cite:name} herumzustochern… tu's nicht :-) Sonst müssen wir manuell mergen ;-)

Ich kümmer mich dann auch gleich um Issue #10 <https://github.com/giovannotti/biblatex-archaeologie/issues/10>. Das gehört ja da mit rein.

**Comment by LukasCBossert** [comment]
Aus:

@Inproceedings{Wulf-Rheidt_2013,
  Title                    = {Der Palast auf dem Palatin -- Zentrum im Zentrum},
  Author                   = {Wulf-Rheidt, Ulrike},
  Editor                   = {Dally, Ortwin and Fless, Friederike and Haensch, Rudolf and Pirson, Felix and Sievers, Susanne},
  Year                     = {2013},
  Eventdate                = {2009-11-18/2009-11-22},
  Eventtitle               = {Internationale Tagung des DAI und des DFG-Exzellenzclusters TOPOI},
  Location                 = {Rahden/Westf.},
  Mainsubtitle             = {Gestaltung – Wahrnehmung – Funktion},
  Maintitle                = {Politische Räume in vormodernen Gesellschaften},
  Pages                    = {277--289},
  Publisher                = {Verlag Marie Leidorf},
  Series                   = {Menschen – Kulturen – Traditionen},
  Subtitle                 = {Geplanter Herrschersitz oder Produkt eines langen Entwicklungsprozesses?},
  Venue                    = {Berlin},
  Volume                   = {6}
}


wird in der Normalausgabe zu:

U. Wulf-Rheidt, Der Palast auf dem Palatin – Zentrum im Zentrum. Geplanter Herrschersitz oder Produkt eines langen Entwicklungspro- zesses?, in: O. Dally – (Hrsg.), Politische Räume in vormodernen Gesellschaften. Gestaltung – Wahrnehmung – Funktion, Bd. 6. In- ternationale Tagung des DAI und des DFG-Exzellenzclusters TOPOI Berlin 18.–22. November 2009, Menschen – Kulturen – Traditionen (Rahden/Westf. 2013) 277–289

Aber mit "hrsgv" zu:

U. Wulf-Rheidt, Der Palast auf dem Palatin – Zentrum im Zentrum. Geplanter Herrschersitz oder Produkt eines langen Entwicklungspro- zesses?, in: Politische Räume in vormodernen Gesellschaften. Gestal- tung – Wahrnehmung – Funktion, Bd. 6, hrsg. v. O. Dally u. a. Internationale Tagung des DAI und des DFG-Exzellenzclusters TOPOI Berlin 18.–22. November 2009, Menschen – Kulturen – Traditionen (Rahden/Westf. 2013) 277–289


Es fehlt in der Normalausgabe das "u.a."

**Comment by giovannotti** [comment]
Huch, ja. Ich kümmer mich drum. Woran das wohl liegt? vielleicht am Bibstyle inproceedings.

**Comment by LukasCBossert** [comment]
Ja, ich denke wg inproceedings. Solle leicht zu beheben sein. Denke ich 😊

--- gesendet von unterwegs ---

**Comment by LukasCBossert** [comment]
habe es behoben. es fehlte : -\value{listtotal} als weiteres optionales Argument.
Ich schließe das issue daher wieder.
