### ISSUE TITLE
Auslagerung von dai-abkuerzungen.bib

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#50]
habe die > @strings< in die Datei "dai-abkuerzungen.bib" ausgelagert.
Bin mir noch nicht sicher, ob das jetzt wirklich funktioniert, oder ob man die wie die lbx-Datei auch aktivieren muss.

**Comment by LukasCBossert** [comment]
Auslagerung funktioniert.

**Comment by moewew** [comment]
Mir ist gerade aufgefallen, dass die `dai-abkuerzungen.bib` zur Zeit noch den Block
```
\ProvidesFile{dai-abkuerzungen.bib}%
               [2015/11/11 v1.2  archaeologie --%
                biblatex fuer Archaeologen, Historiker und Philologen, bib-Datei]
```
enthält. 

`.bib`-Dateien identifizieren sich normalerweise nicht mit `\ProvidesFile`, Biber schimpft auch ein wenig (`characters of junk seen at toplevel`).

Dasselbe gilt auch für `archaeologie.bib`. Auch dort sollte
```
\ProvidesFile{archaeologie.bib}%
               [2015/11/11 v1.2  archaeologie --%
                biblatex fuer Archaeologen, Historiker und Philologen, bib-beispiel-Datei]
```

besser verschwinden.

**Comment by LukasCBossert** [comment]
Ah - und ich habe mich gewundert, warum ich gestern auf einmal Fehlermeldungen bei `dai-abkuerzungen.bib` bekomme. Danke für den Hinweis. Ich lösche die Einträge.
