### ISSUE TITLE
namea

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#52]
Dem Feld `namea` kann mit Biber ein schönerer Name gegeben werden, der etwas sprechender ist. Dafür müsstet ihr euch dann aber datamodels und `.dbx`-Dateien ansehen.

**Comment by moewew** [comment]
Vielleicht ist eure Nutzung von `namea` ja mit dem Standard-Feld `shortauthor` identisch. Ich sehe es nur einmal in `cite:name` genutzt.

**Comment by LukasCBossert** [comment]
ja, das klingt nach einer guten Lösung! werde ich umsetzen. habe an `shortauthor`nicht gedacht.

**Comment by moewew** [comment]
Wenn ihr in den Zitatbefehlen durchgehend `labelname` nutzt, wird `shortauthor` automatisch der Vorzug vor `author` gegeben, ich denke, ihr könntet damit fast das ganze Makro `cite:name` auf `\printfield{labelname}` eindampfen. Und dann je nach Optionen am `uniquename` (siehe https://github.com/giovannotti/biblatex-archaeologie/issues/38) basteln

z.B.

```
\renewbibmacro*{cite:name}{% 
  \c@uniquename=0% 0: only last names, 1: last name + first name initials, 2: full name
  \ifciteindex{\indexnames{labelname}}{}%
  \printtext[bibhyperref]{%
    \printnames{labelname}}}
```

**Comment by LukasCBossert** [comment]
wow - das wird immer besser. Somit verschlankt sich der Code sehr.

**Comment by LukasCBossert** [comment]
Habe dies mit 
```
\renewbibmacro*{cite:name}{%   % 0: only last names, 1: last name + first name initials, 2: full name
  \ifbool{cbx:vollername}{\c@uniquename=2}{\ifbool{cbx:nurnachname}{\c@uniquename=0}{\c@uniquename=1}}
  \ifciteindex{\indexnames{labelname}}{}%
  \printtext[bibhyperref]{%
    \iffootnote{\c@uniquename=0 \printnames{labelname}}{\printnames{labelname}}}}
```
umgesetzt und bin sehr zufrieden.
