### ISSUE TITLE
`miturl`

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#53]
Die Option `miturl` sollte eigentlich durch die schon vorhandenen Optionen `url`, `doi`, `eprint` schon implementiert sein, scheint mir also überflüssig. Es ist übrigens so, dass `miturl=falsch` automatisch dafür sorgt, dass backreferences immer unterdrückt werden, egal was die `backref`-Option sagt.

**Comment by moewew** [comment]
Ein erster Lösungsansatz wird hier wohl daraus bestehen, überall den Schalter `bbx:miturl` zu entfernen, also
```
\ifbool{bbx:miturl}{\usebibmacro{doi+eprint+url}}{}%
```
einfach zu
```
\usebibmacro{doi+eprint+url}%
```
umzubauen.

**Comment by LukasCBossert** [comment]
erledigt.
