### ISSUE TITLE
  \iftoggle{bbx:related}

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#54]
Weiter scheint der 
```
  \iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}%
```
Block nur bei bestimmten Typen und nicht bei allen vorhanden zu sein, in `standard.bbx` haben das alle Typen.

**Comment by LukasCBossert** [comment]
hm - ich fürchte, dass das ein Überbleibsel aus der Vorlage `geschichtsfrkl`ist - kann vermutlich gelöscht werden?!

**Comment by giovannotti** [comment]
sieht so aus. Lösch es einfach mal :)

**Comment by LukasCBossert** [comment]
gelöscht

**Comment by moewew** [comment]
Damit verliert ihr natürlich die schöne related-Funktion von `biblatex`. Spricht denn etwas dagegen, es überall hinzuzufügen?

**Comment by giovannotti** [comment]
Wegen mir gerne. (Ich habe die related-Funktion noch nie benutzt.)

**Comment by moewew** [comment]
Das sollte eigentlich nicht viel komplizierter sein, als den Block
```
  \newunit\newblock
  \iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}%
```
in allen Drivers 
direkt vor `\usebibmacro{savestuff}%` anzubringen.

Die `related`-Funktionalität bietet einige sehr nette Funktionen, z.B. können so ein Werk und seine Übersetzung zusammengebracht werden (`vangennep:related` und `vizedom:related` in `biblatex-examples.bib`), oder ein Multivolumebuch und die Einzelwerke (`knuth:ct:related`) .

**Comment by giovannotti** [comment]
Was ist dann genau der Unterschied zwischen `crossref` und `related`? Geht es dann da nicht um die bloße Übernahme der Daten wie bei `crossref` sondern um eine Zitatergänzung? Ich muss das mal ausprobieren...

**Comment by moewew** [comment]
Es geht eher um zusätzliche Informationen in der Bibliographie als um das Zitat selbst. Felder werden mit `related` nicht vererbt, dafür ist in der Tat `crossref` da. Die Informationen in `crossref` gliedern sich in den Eintrag ganz normal ein und sind im Literaturverzeichnis am Ende gar nicht mehr von den nicht vererbten Feldern zu unterscheiden. Die `related`-Informationen werden aber sehr deutlich vom Rest separiert.

Zum Probieren
```
\documentclass[a4paper,british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}
\usepackage[style=verbose-note]{biblatex}

\addbibresource{biblatex-examples.bib}


\begin{document}
\begin{refsection}
  \nocite{knuth:ct:related,kullback:related,moore:related,vangennep:related,vizedom:related,doody}
  \printbibliography[title=related]
\end{refsection}

\begin{refsection}
  \nocite{westfahl:space}
  \printbibliography[title=crossref]
\end{refsection}
\end{document}
```

**Comment by giovannotti** [comment]
Das ist ja eine großartige Funktion. Die wird bei mir mit Sicherheit Verwendung finden.
Danke für die Info!!
Ich baue sie freilich ein.
