### ISSUE TITLE
maintitle vs. booktitle

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#55]
Schließlich scheint mir bei `@incollection`s (`@inbook`s) der `booktitle` nicht richtig zu funktionieren, es wird nur `maintitle` beachtet. In der Tat scheint es mir so, dass in der Beispieldatei `archaeologie.bib` bei den  `@in...`-Einträgen eigentlich immer `booktitle` statt `maintitle` genutzt werden sollte.

**Comment by LukasCBossert** [comment]
Kann dies nicht mit `\DeclareBibliographyAlias{maintitle}{booktitle}`behoben werden? Dann ist es egal, ob man `maintitle`oder `booktitle`wählt!?

**Comment by moewew** [comment]
Nein `\DeclareBibliographyAlias` ist nur für Eintragstypen und nicht für bestimmte Felder (eine Erklärung dazu gibt es bei [TeX.SX](http://tex.stackexchange.com/q/268553/35864)).

Außerdem sind `maintitle` und `booktitle` zwei sehr unterschiedliche Konzepte.
`maintitle` ist für Titel von mehrbändigen Werken; `booktitle` ist einfach nur für den Titel des Werkes, in dem man ein `@in...`-Werk findet. Beispiele dazu gibt es in `biblatex-examples.bib`.

Man könnte mit Biber die beiden Felder zusammenwerfen, aber ich kann das Auf keinen Fall empfehlen, es gibt Fälle, in denen man sowohl ein `maintitle` als auch einen `booktitle` braucht.
Z.B.
```
@inbook{kant:kpv,
  title        = {Kritik der praktischen Vernunft},
  date         = 1968,
  author       = {Kant, Immanuel},
  booktitle    = {Kritik der praktischen Vernunft. Kritik der Urtheilskraft},
  bookauthor   = {Kant, Immanuel},
  maintitle    = {Kants Werke. Akademie Textausgabe},
  volume       = 5,
  publisher    = {Walter de Gruyter},
  location     = {Berlin},
  pages        = {1-163},
  shorthand    = {KpV},
}
```
aus `biblatex-examples.bib`

**Comment by LukasCBossert** [comment]
Habe alles auf `booktitle` umgestellt. Ich hoffe, das passt alles.

**Comment by moewew** [comment]
Im `.bib` file sieht das alles sinnvoll aus, wobei man bei den `@inreferences` die `maintitle` hätten bleiben können, das ist aber eher eine Detailfrage. Ich sehe aber, dass nun in der `.bbx` gar keine `maintitle` mehr vorkommen?

**Comment by LukasCBossert** [comment]
ja, das habe ich mir gedacht, dass die `maintitle`jetzt komplett rausgeflogen sind. 
ist ausreichend wenn man das makro `\usebibmacro{maintitle}`einbaut?

**Comment by moewew** [comment]
Ich würde diese Teile ja so gut wie möglich aus `standard.bbx` abschreiben und dann mit euren Vorgaben vergleichen (so wie ich viele Vorgaben kenne, haben sie daran nicht gedacht, und dann macht ihr es wie ihr es schöner findet.). Grob gesehen unterscheidet  `standard.bbx` zwei Makros `maintitle+title` für `book`, `collection` und so, und `maintitle+title` für `@in...`-Typen. Für `@online` und `@article` gibt es nur ein `title`-Makro, denn die haben weder `maintitle` noch `booktitle`.

**Comment by LukasCBossert** [comment]
sollte nun umgesetzt sein.
