### ISSUE TITLE
maxibibnames=999

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#58]
Bei dem `author`-Makro ist das ganz einfach. Wenn man `maxbibnames=999` setzt, um alle Autoren anzuzeigen, könnt ihr euch

```
\renewbibmacro*{author}{%
  \ifnameundef{author}{}{%
        \printnames[][-\value{listtotal}]{author}\newunit%
      }}%
```

sparen.

Die Redefinition von `author/editor` ist auch nicht mehr nötig, wenn wir stattdessen

```
\DeclareFieldFormat{editortype}{\mkbibparens{#1}}
\renewbibmacro*{editor}{%
  \ifboolexpr{
    test \ifuseeditor
    and
    not test {\ifnameundef{editor}}
  }
    {\printnames{editor}%
     \setunit{\addspace}%
     \usebibmacro{editorstrg}%
     \clearname{editor}}
    {}}
```
nutzen. Das reicht noch nicht ganz für die Funktion von `frgantik`, das kann aber mit

```
\DeclareEntryOption{frgantik}[true]{%
  \ifstrequal{#1}{true}{\togglefalse{blx@useauthor}}{}%
  \csuse{bool#1}{cbx:frgantik}%
}%
```

sofort nachgerüstet werden. Wenn allerdings `frgantik` nie einen Autor haben, dann kann dort auch die ursprüngliche Definition bleiben.

**Comment by LukasCBossert** [comment]
habe ich soweit umgesetzt, allerdings funktioniert jetzt die Labelauflösung in der Bibliographie nicht mehr. Es wird nicht mehr nur der erste Autor und "u.a." angezeigt und dann alle Autoren aufgeführt, sondern es werden alle Autoren sowohl als Label als auch in der bibliographischen Angabe angezeigt.

**Comment by moewew** [comment]
Ja, das liegt daran, dass ihr wollt, dass der Block in `begentry` bzw. der Beginn von `\defbibenvironment` sich so verhält, als wäre er ein Zitat und nicht in der Bibliographie, dort sollen also `maxcitenames` und Konsorten gelten und wenn es geht auch die `\mkbibnamelast` für Zitate und nicht Bibliographien.

Bei TeX.SX gibt es da eine Lösung für `maxnames` in [Adding an [AuthorYear] block at the beginning of bibliography entries](http://tex.stackexchange.com/q/11827/35864), es wird der Zähler für die Zitate einfach zwischengespeichert. Möglicherweise gibt es noch eine elegantere Lösung ...
Die Schriftarten für die Zitate könnt ihr auch lokal in `begentry` zurücksetzen.
Ihr solltet darüber nachdenken, den Kram in `\defbibenvironment` in ein Makro auszulagern, das ist ein bisschen sauberer.

Mir scheint
```
\newbibmacro{labelwidthbib}{%
  \csuse{blx@hook@cite}%
  \csuse{blx@hook@citekey}%
  \defcounter{maxnames}{\blx@maxcitenames}%
  \ifbool{cbx:unbekannt}
    {\usebibmacro{shorthand+year}}
    {\ifboolexpr{bool {cbx:antik}%
                 or bool {cbx:frgantik}% 
                 or bool {cbx:nurshorthand}}%
       {\printfield{shorthand}}%
       {\printnames{labelname}%
        \setunit{\addspace}%
        \printtext[citeyear]{%
          \printfield{labelyear}\printfield{extrayear}}}}}

\DeclareFieldFormat{shorthandwidth}{#1}

\defbibenvironment{bibliography}
  {\list
     {\usebibmacro{labelwidthbib}}
     {\setlength{\labelwidth}{\shorthandwidth}%
      \addtolength{\labelwidth}{4pt}%<---- warum ich das brauche, habe ich nicht ganz raus, sonst ist die Liste an einigen Stellen zu weit eingerückt???
      \setlength{\leftmargin}{\labelwidth}%
      \setlength{\labelsep}{\biblabelsep}%
      \addtolength{\leftmargin}{\labelsep}%
      \setlength{\itemsep}{\bibitemsep}%
      \setlength{\parsep}{\bibparsep}%
      \renewcommand*{\makelabel}[1]{##1\hss}}}
  {\endlist}
  {\item}
```
eine ganz nette Lösung für den Anfang.

Wenn das `cite` bibmacro noch ein bisschen aufgeräumt wird, wäre sogar
```
\newbibmacro{labelwidthbib}{%
  \defcounter{maxnames}{\blx@maxcitenames}\usebibmacro{cite}}
```
möglich.

**Comment by moewew** [comment]
Damit ist auch die Small-Caps-Geschichte in https://github.com/giovannotti/biblatex-archaeologie/issues/38 geklärt, wenn ihr `\AtEveryCite` nutzt, natürlich kann ein `\AtBeginBibliography` nicht rückgängig gemacht werden.

**Comment by moewew** [comment]
Oben habe ich vergessen, zu lange labels, in die nächste Zeile zu kicken, das geht mit

```
\AtBeginBibliography{\renewbibmacro{begentry}{\usebibmacro{kicklabel}}}

\newbibmacro{kicklabel}{% 
  \sbox\arch@labelbox{\usebibmacro{labelwidthbib}}%
  \global\togglefalse{blx@insert}%
  \ifdim\shorthandwidth<\wd\arch@labelbox\newline\fi}
```

zusammen also

```
\newbibmacro{labelwidthbib}{%
  \csuse{blx@hook@cite}%
  \csuse{blx@hook@citekey}%
  \defcounter{maxnames}{\blx@maxcitenames}%\usebibmacro{cite}%
  \ifnameundef{labelname}
    {\usebibmacro{shorthand+year}}
    {\ifboolexpr{bool {cbx:antik}%
                 or bool {cbx:frgantik}% 
                 or bool {cbx:nurshorthand}}%
       {\printfield{shorthand}}%
       {\printnames{labelname}%
        \setunit{\addspace}%
        \printtext[citeyear]{%
          \printfield{labelyear}\printfield{extrayear}}}}}

\DeclareFieldFormat{shorthandwidth}{#1}

\AtBeginBibliography{\renewbibmacro{begentry}{\usebibmacro{kicklabel}}}

\newbibmacro{kicklabel}{% 
  \sbox\arch@labelbox{\usebibmacro{labelwidthbib}}%
  \global\togglefalse{blx@insert}%
  \ifdim\shorthandwidth<\wd\arch@labelbox\newline\fi}

\defbibenvironment{bibliography}
  {\list
     {\usebibmacro{labelwidthbib}}
     {\setlength{\labelwidth}{\shorthandwidth}%
      \setlength{\leftmargin}{\labelwidth}%
      \setlength{\labelsep}{\biblabelsep}%
      \addtolength{\leftmargin}{\labelsep}%
      \setlength{\itemsep}{\bibitemsep}%
      \setlength{\parsep}{\bibparsep}%
      \renewcommand*{\makelabel}[1]{##1\hss}}}
  {\endlist}
  {\item}
```

**Comment by LukasCBossert** [comment]
übernommen. funktioniert prima

**Comment by moewew** [comment]
Ich habe mir das gerade nochmal angesehen und finde die folgende Lösung etwas schöner

```
\newbibmacro{labelwidthbib}{%
  \csuse{blx@hook@cite}%
  \csuse{blx@hook@citekey}%
  \defcounter{maxnames}{\blx@maxcitenames}%\usebibmacro{cite}%
  \ifnameundef{labelname}
    {\usebibmacro{shorthand+year}}
    {\ifboolexpr{bool {cbx:antik}%
                 or bool {cbx:frgantik}% 
                 or bool {cbx:nurshorthand}}%
       {\printfield{shorthand}}%
       {\printnames{labelname}%
        \setunit{\addspace}%
        \printtext[citeyear]{%
          \printfield{labelyear}\printfield{extrayear}}}}}

\DeclareFieldFormat{shorthandwidth}{#1}

\newbibmacro{kicklabel}{% 
  \sbox\arch@labelbox{\usebibmacro{labelwidthbib}}%
  \global\togglefalse{blx@insert}%
  \ifdim\shorthandwidth<.9\wd\arch@labelbox\newline\fi}

\defbibenvironment{bibliography}
  {\list
     {\usebibmacro{labelwidthbib}}
     {\setlength{\labelwidth}{\shorthandwidth}%
      \setlength{\leftmargin}{\labelwidth}%
      \setlength{\labelsep}{\biblabelsep}%
      \addtolength{\leftmargin}{\labelsep}%
      \setlength{\itemsep}{\bibitemsep}%
      \setlength{\parsep}{\bibparsep}%
      \renewcommand*{\makelabel}[1]{##1\hss}}}
  {\endlist}
  {\item\leavevmode\usebibmacro{kicklabel}}
```

Da muss `begentry` nicht umdefiniert werden, außerdem habe ich die `.9` wieder geholt. Eine schönere Lösung würde übrigens oben in `labelwidthbib` einfach nur `\usebibmacro{cite}` nutzen, aber zur Zeit geht das noch nicht ganz, da es noch ein paar Zeichensetzungsprobleme macht.

Das Komma, was erschien, wenn kein Autor oder Herausgeber da war, kam, da in `\sbox\arch@labelbox{\usebibmacro{labelwidthbib}}` der Text quasi "unsichtbar" gesetzt wird, `biblatex` aber denkt, es hätte sichtbaren Text in der Bibliographie ausgegeben (und müsste daher dann auch Zeichensetzung folgen lassen), mit dem `\global\togglefalse{blx@insert}%` treiben wir ihm diesen Unsinn aus.

**Comment by LukasCBossert** [comment]
ziemlich cool. funktioniert.
