### ISSUE TITLE
\newunitpunct bei fehlenden Autor-/Editor-Daten

### ISSUE THREAD

**Issue by giovannotti** [giovannotti/biblatex-archaeologie#59]
Gibt es eine andere Möglichkeit als über

```
\usebibmacro{author/editor}%
\ifboolexpr{test {\ifnameundef{author}} and test {\ifnameundef{editor}}}%
  {}%
  {\newunit\newblock}%
\usebibmacro{title}%
```

das newunitpunct-Komma bei fehlenden Autor-/Editor-Daten am Anfang eines Zitats zu unterdrücken?

**Comment by moewew** [comment]
Ich habe jetzt nicht rumporbiert, aber probiert es mal mit den gesternten Version von `\setunit`
```
  \usebibmacro{author/editor}%
  \setunit*{\labelnamepunct}\newblock
  \usebibmacro{title}%
```
da wird dann auch das schöne `\labelnamepunct` wie in `standard.bbx` genutzt.

**Comment by moewew** [comment]
Das scheint es jetzt doch nicht zu tun. Ich halte es immer noch für ein gutes Feature `\labelnamepunct` zu setzten. Wenn ihr etwas wie meinen Vorschlag in https://github.com/giovannotti/biblatex-archaeologie/issues/58 nutzt, erledigt sich dieses Problem aber von selbst.

**Comment by giovannotti** [comment]
Ja ich hatte auch schon `\setunit*{\newunitpunct}\newblock` versucht, aber ohne Erfolg. Ich setzt nun mal die korrekte Form `\setunit*{\labelnamepunct}\newblock`um und dann schauen wir, dass wir mit #58 weiterkommen.
