### ISSUE TITLE
Neuaufbau von bbx und cbx

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#6]
Wie wäre es, bbx und cbx nochmal (grundlegend) neu aufzubauen, sodass die Option "dai" standardmäßig geladen wird (jetzt ist das Autor-Titel) und alle dafür notwendigen Veränderungen, die momentan über weitere Optionen geladen werden. (Bezieht sich ggf. nur auf die bbx-Datei)
Dann kann man optional "dai-verweis" und weitere Optionen bauen, bspw. Nennung von Übersetzer, Originaltitel, Sprache; alle Verlagsorte und Verlag.

Damit wird der gesamte Code m.E. entschlackt und ist nun wirklich fokussiert auf die DAI-Richtlinie und als Schmankerl gibt es eben die weiteren Optionen.

**Comment by LukasCBossert** [comment]
Habe ich jetzt schon angefangen und sieht sehr gut aus: der Stil heißt "neu-archaeologie"(.bbx/.cbx)
Der Code ist schlanker und cbx:autorjahr ist rausgeflogen, da dies ja standardmäßig DAI ist.
Es sind noch kleine Verbesserungen nötig (Namensformatierung in Bibliographie), ansonsten besteht nach wie vor das Problem von "u. a."

**Comment by giovannotti** [comment]
Super, die Idee finde ich sehr gut. Montag vormittag mach ich wieder mit.

**Comment by LukasCBossert** [comment]
Prima, dann arbeiten wir an der neuen Datei weiter. Habe schon was hochgeladen und den Stil bei Academia.edu angekündigt. Da kann man github prima integrieren...

--- gesendet von unterwegs ---

**Comment by LukasCBossert** [comment]
ich habe gerade mal etwas aufgeräumt.
Mein Vorschlag ist, dass wir im Zwei „WorkInProgress“ arbeiten und im Hauptzweig (master - bzw. Beta-Version) nur die Stil-Dateien und Beschreibung laden, sodass das der „öffentliche“ Ordner ist, aus dem man den Stil sich herunterladen kann.

Alles weitere zum Code siehst du in „archaeologie.tex“ - ich bin morgen auch online, dann können wir weiter tüfteln.

 
Am 28.06.2015 um 18:36 schrieb Johannes <notifications@github.com>:

Super, die Idee finde ich sehr gut. Montag vormittag mach ich wieder mit.

**Comment by giovannotti** [comment]
Einverstanden. Ich orientiere mich.
