### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#60]
Es gibt sicherlich auch eine Möglichkeit `\DeclareBibliographyDriver{review}`geschickter zu programmieren, auch wenn der Output genauso bleiben soll.

```
\DeclareBibliographyDriver{review}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
  \usebibmacro{author/editor}
  \setunit*{\labelnamepunct}\newblock%
    \iffieldundef{title}{}{\printfield{title}}%
   \iffieldundef{titleaddon}{}{%
   	\newunit\newblock
   			\bibstring{review}%
			\setunit{\addnbspace}%
 			\printfield{titleaddon}%
 			}%
  \newunit\newblock
  \usebibmacro{journal+number+year}%
  \newunit\newblock%
  \usebibmacro{pages}%
  \ifbool{bbx:miturl}{\usebibmacro{doi+eprint+url}}{}%
  \usebibmacro{signatur}%
  \newunit\newblock
  \iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}%
  \usebibmacro{savestuff}%
  \usebibmacro{finentry}%
}%

```

Ich denke dabei vor allem an den Eintrag in `titleaddon`, der mit `\fullcite{XY}`ausgefüllt sein muss.
Gibt es da nicht die Möglichkeit in den `\DeclareBibliographyDriver{review}` zu schreiben, dass ein `\fullcite`stattfinden soll? Und es gibt sicherlich auch ein besseres Feld dafür als das aktuelle `titleaddon`.

```
@Book{Welch_2007,
  Title                    = {The {Roman} Amphitheatre},
  Author                   = {Welch, Katherine E.},
  Location                 = {Cambridge and New York},
  Publisher                = {CUP},
  Subtitle                 = {From its Origins to the Colosseum},
  Year                     = {2007}
}
@Review{Bell_2011,
  Author                   = {Bell, Sinclair},
  titleaddon = {\fullcite{Welch_2007}},
  Number                   = {1},
  Volume                   = {115},
  pages = {1--4},
  Year                     = {2011},
  Journaltitle             = AJA-lang,
  Publisher                = {Archaeological Institute of America},
  Shortjournal             = AJA-kurz,
}
@Review{Hufschmid_2010,
  Title                    = {Von Caesars \emph{theatron kynegetikon} zum \emph{amphitheatrum novum} Vespasians},
  titleaddon = {\fullcite{Welch_2007}},
  Author                   = {Hufschmid, {Th}omas},
  Pages                    = {487--504},
  Volume                   = {23},
  Year                     = {2010},
  Journaltitle             = JRA-lang,
  Shortjournal             = JRA-kurz,
}
```

**Comment by LukasCBossert** [comment]
Stelle gerade fest, dass ja diese `related`-Sache (#54) sich auch - mit ein paar Modifikationen - sehr gut für die Rezensionen eigenen würde!? Damit spart man sich die `fullcite`-Angabe.

**Comment by LukasCBossert** [comment]
Ich denke, es funktioniert!!!! Siehe commit.

**Comment by moewew** [comment]
Das ist eine gute Idee. Vielleicht solltet ihr dem `related` auch noch ein `relatedtype= {review},` oder so zur Seite stellen. Dann wird nämlich automatisch der bibstring "Rez.zu" ausgegeben.
Ihr könnt dann den Block
```
\iffieldundef{related}{}{\bibstring{review}%
			\setunit{\addnbspace}}%
```
entfernen. Ferner würde ich statt
```
\iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}% 			%
```
auf hier auf jeden Fall nur
```
\usebibmacro{related:init}
\usebibmacro{related}%
```
nutzen. Dann kann man das nicht versehentlich ausschalten. 

Ich würde euch außerdem empfehlen, eins spezielles Makro `related:review` zu definieren, da ihr mit dem Standard zur Zeit zufrieden seid, reicht auch
```
\newbibmacro*{related:review}[1]{\usebibmacro*{related:default}{#1}}
```
aber dann könnt ihr das Aussehen in Zukunft besser steuern.

**Comment by LukasCBossert** [comment]
Cool - es gibt noch viel zu Lernen und entdecken. Habe mir gedacht, dass es so etwas wie `relatedtype= {review}' gibt. Wird eingebaut.

**Comment by moewew** [comment]
Ich würde den typen wohl lieber `reviewof` nennen, dann müsstet ihr aber zusätzlich euren bibstring von `review` zu `reviewof` umbenennen. (Die Idee hier ist, dass `biblatex` immer versucht, den bibstring der den Namen des `relatedtype` trägt, einzufügen.)

**Comment by LukasCBossert** [comment]
prima. umgesetzt.

**Comment by moewew** [comment]
Hupps, dann müsste es natürlich auch `\newbibmacro*{related:reviewof}[1]{\usebibmacro*{related:default}{#1}}` heißen....

**Comment by LukasCBossert** [comment]
habe ich geändert. habe erstmal keinen Unterschied festgestellt.

**Comment by moewew** [comment]
Ja, das ist korrekt, es sollte keine Änderung geben. Eigentlich ist diese Definition auch gar nicht notwendig, da standardmäßig auf `related:default` zurückgegriffen wird, wenn kein passendes Makro gefunden wurde.
