### ISSUE TITLE
journaltitle und shortjournal

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#61]
Aktuell gibt es das `journaltitle`und `shortjournal`mittles `@string`auszugeben, wofür die Ergänzungen `-lang`bzw. `-kurz`notwendig sind:

```
@Article{Koyunlu_1990,
author = {Koyunlu, A.},
title = {Die Bodenbelage und der Errichtungsort der Hagia Sophia},
pages = {147--156},
volume = {11},
year = {1990},
journaltitle = AyasofyaMuezYil-lang,
shortjournal = AyasofyaMuezYil-kurz
}
```

Gibt es eine Möglichkeit, dass die Ergänzungen `-lang`bzw. `-kurz` automatisch ergänzt werden? 

Bzw. gibt es eine bessere Möglichkeit die Ausgabe der Zeitschriften zu steuern, sodass man im Bibliographieeintrag nur noch den `@string`einträgt und dann mittels der Option `{bbx:keineabkuerzung}` automatisch die Ausgabe gesteuert wird?

**Comment by moewew** [comment]
Ihr könntet die `dai-abkuerzungen.bib` aufsplitten in `dai-abkuerzungen-kurz.bib` und `dai-abkuerzungen-lang.bib` mit offensichtlichem Inhalt.
Dann entfernt ihr aber das `-kurz` und `-lang` aus dem `@string`-Namen.
Z.B. enthielte `dai-abkuerzungen-kurz.bib` 
```
@String {AbhGoettingen = {AbhGöttingen}}
@String {AyasofyaMuezYil= {AyasofyaMüzYıl}}
@String {GFA= {GFA}}
@String {GGA= {GGA}}
```
und `dai-abkuerzungen-lang.bib` dann
```
@String {AbhGoettingen = {Abhandlungen der Akademie der Wissenschaften zu Göttingen. Philologisch-Historische Klasse}}
@String {AyasofyaMuezYil= {Ayasofia Müzesi yıllığı. Annual of Ayasofya Museum}}
@String {GFA= {Göttinger Forum für Altertumswissenschaft}}
@String {GGA= {Göttingische Gelehrte Anzeigen}}
```

Dann könnt ihr je nach Option `bbx:keineabkuerzung` entscheiden, ob ihr `dai-abkuerzungen-kurz.bib` oder `dai-abkuerzungen-lang.bib` ladet.

In der `.bib`-Datei haben wir dann nur noch
```
@Article{Koyunlu_1990,
  author = {Koyunlu, A.},
  title = {Die Bodenbelage und der Errichtungsort der Hagia Sophia},
  pages = {147--156},
  volume = {11},
  year = {1990},
  journaltitle = AyasofyaMuezYil,
}
```

**Comment by moewew** [comment]
Alternativ, könnt ich euch mal `xdata` ansehen, da können zugleich mehrere Felder übernommen werden. Der Nachteil da ist, dass der "Empfängereintrag" `xdata`s standardmäßig nur im `xdata`-Feld annimmt, also hättet ihr 

```
@xdata{AyasofyaMuezYil,
  shortjournal = {AyasofyaMüzYıl},
  journaltitle  = {Ayasofia Müzesi yıllığı. Annual of Ayasofya Museum},
}

@Article{Koyunlu_1990,
  author = {Koyunlu, A.},
  title = {Die Bodenbelage und der Errichtungsort der Hagia Sophia},
  pages = {147--156},
  volume = {11},
  year = {1990},
  xdata = {AyasofyaMuezYil},
}
```

Allerdings kann man das mit einer Biber sourcemap
```
\DeclareSourcemap{
  \maps{
    \map[overwrite=true]{
      \step[fieldsource=xdata, final]
      \step[fieldsource=xjournal, final]
      \step[fieldset=xdata, fieldvalue={,}, append]
      \step[fieldset=xdata, origfieldval, append]
      \step[fieldset=xjournal, null]
    }
    \map[overwrite=true]{
      \step[fieldsource=xjournal, final]
      \step[fieldset=xdata, origfieldval, append]
    }
  }
}
```
(vielleicht geht das noch einfacher, aber nur so konnte ich das wirklich robust machen)
zu
```
@Article{Koyunlu_1990,
  author = {Koyunlu, A.},
  title = {Die Bodenbelage und der Errichtungsort der Hagia Sophia},
  pages = {147--156},
  volume = {11},
  year = {1990},
  xjournal = {AyasofyaMuezYil},
}
```
umbauen.

**Comment by LukasCBossert** [comment]
Ich finde die erste Option intuitiver und stringenter wenn man auch Zeitschriftentitel hat, die nicht über einen `@string`laufen.

Allerdings fürchte ich, dass dann das folgende nicht mehr funktioniert: 
```
\defbibcheck{shortseries}{%	
    \iffieldundef{shortseries}{\skipentry}{}%
    \iffieldundef{series}{\skipentry}{%
        \ifcsdef{\strfield{series}}{\skipentry}{\savefieldcs{series}{\strfield{series}}}%   
            }}%  
\defbibcheck{shortjournal}{%
    \iffieldundef{shortjournal}{\skipentry}{}%
    \iffieldundef{journaltitle}{\skipentry}{%
        \ifcsdef{\strfield{journaltitle}}{\skipentry}{\savefieldcs{journaltitle}{\strfield{journaltitle}}}%   
            }}%
```
--> Sodass in einer extra Bibliographie `\printbiblist[heading=subbibnumbered,title={Zeitschriftenabkürzungen}]{shortjournal}`die Zeitschriftenkürzel aufgelöst werden.

**Comment by LukasCBossert** [comment]
Ah, sehe gerade, dass du meine Befürchtung bestätigst....

Würde die `\printlist`-Funktion mit `xdata`funktionieren?

**Comment by moewew** [comment]
Ich denke ja. Denn für `biblatex` sieht es am Ende so aus, als seien `shortjournal` und `journal` ganz normal gefüllt.

**Comment by LukasCBossert** [comment]
Dann gilt es nur abzuwägen, ob die Schreibweise mit `-lang`und `-kurz`oder die Verwendung des Feldes `xjournal`intuitiver und weniger aufwändig ist.

**Comment by giovannotti** [comment]
@LukasCBossert schließen?

**Comment by LukasCBossert** [comment]
ja, denn je mehr ich drüber nachdenke, finde ich die vielleicht etwas unhandlich scheinende Variante mit `-kurz`und `-lang` doch besser, weil man 1) die Abkürzungen auflösen kann, 2) nicht umdenken muss beim Ausfüllen der Felder.
