### ISSUE TITLE
Kein Komma zwischen booktitle und volume

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#62]
Nach den DAI-Vorgaben darf kein Komma zwischen `title`/`booktitle`und `volume`sein:

```M. Tullius Cicero, Rede für P. Sestius, pro P. Sestio, aus dem Lateinischen übers. von M. Fuhrmann, in: M. Fuhrmann (Hrsg.), Die politischen Reden, II, Sammlung Tusculum (München 1993) 110–185```

Es müsste also lauten:

```M. Tullius Cicero, Rede für P. Sestius, pro P. Sestio, aus dem Lateinischen übers. von M. Fuhrmann, in: M. Fuhrmann (Hrsg.), Die politischen Reden II, Sammlung Tusculum (München 1993) 110–185```

**Comment by LukasCBossert** [comment]
Wie es mir scheint, steckt das Problem mit dem Komma in 

```
\renewbibmacro*{maintitle+booktitle}{%
  \iffieldundef{maintitle}
    {}
    {\usebibmacro{maintitle}%
     \newunit\newblock
     \iffieldundef{volume}
       {}
       {\printfield{volume}%
        \printfield{part}%
        \setunit{\addcolon\space}}}%
  \usebibmacro{booktitle}
  }
  
```
und speziell bei `\usebibmacro{booktitle}` wo sich wohl am Ende ein `\newunit` verbirgt. 
Allerdings finde ich nirgendwo (auch nicht in der `standard.bbx`) das Makro definiert. ???

**Comment by moewew** [comment]
Es wohnt in `biblatex.def`

```
\newbibmacro*{booktitle}{%
  \ifboolexpr{
    test {\iffieldundef{booktitle}}
    and
    test {\iffieldundef{booksubtitle}}
  }
    {}
    {\printtext[booktitle]{%
       \printfield[titlecase]{booktitle}%
       \setunit{\subtitlepunct}%
       \printfield[titlecase]{booksubtitle}}%
     \newunit}%<---- da ist ein `\newunit`
  \printfield{booktitleaddon}}
```

Aber ich denke, dass ihr hier statt `volume` eigentlich `number` braucht. Als Faustregel gilt `maintitle` und `volume` gehören zusammen, `series` und `number` gehören zusammen (bei [TeX.SX](http://tex.stackexchange.com/q/270399/35864)). "Sammlung Tusculum" sieht mir eher nach einer Schriftenreihe (`series`) aus. (Als Faustregel gilt: Viele Bände & mehre Herausgeben: `series`; eher weniger Bände und eine feste Gruppe an Autoren/Herausgebern: `maintitle`.)

**Comment by LukasCBossert** [comment]
Aha - in der `biblatex.def`habe ich natürlich nicht nachgeschaut.
Dennoch: Wenn ich `\newunit`entferne, verschwindet das Komma, dafür kommt nun der `\subtitlepunct`obwohl in diesem Beispiel ja kein Untertitel definiert ist.

Kann ein `booktitle`kein `volume`haben? Im gewählten Beispiel ist "Sammlung Tusculum" die Reihe (`series`), hat aber keine laufende Nummer. Dafür liegt in "Die politischen Reden" in drei Bänden vor. Es käme mir aber falsch vor, "Die politischen Reden" in `maintitle`zu setzen, da dann ja ein `booktitle`fehlt.

**Comment by moewew** [comment]
Ich bin gerade nicht sicher, in welchem Makro genau das Problem liegt, aber es ist wohl am einfachsten, `{booktitle}` so zu lassen und, bevor ihr das `volume` druckt, einfach `\setunit{addspace}` zu setzten.

Also z.B. (es gibt noch mehr Stellen)

```
\usebibmacro{booktitle}%
\setunit{\addspace}%
\usebibmacro{volume}%
```

statt

```
\usebibmacro{booktitle}%
\usebibmacro{volume}%
```

und das auch für `\usebibmacro{maintitle+booktitle} \usebibmacro{volume}%`.

Ich würde es meiner Faustregel folgend nicht schlimm finden, wenn wir keinen `booktitle` haben sondern nur einen `maintitle` mit `volume`. Aber da kann es sicher zwei Meinungen geben, am Ende ist das Ergebnis entscheidend.

**Comment by LukasCBossert** [comment]
ok, habe ` \setunit{\addspace}` an entsprechenden Stellen ergänzt und jetzt ist das Ergebnis wie es sein soll.
Daher habe ich die Makros `maintitle+title`und `booktitle`gelöscht, bzw. auf die `standard.bbx`zurückgreifen lassen.
