### ISSUE TITLE
Bibliographie-label bei `@inreference` und Option `lexika`

### ISSUE THREAD

**Issue by giovannotti** [giovannotti/biblatex-archaeologie#67]
1) Das Bib-Label für `@inreference` bei gewählter cbx-Option `lexika` gibt bei mir in der Bibliographie den gesamten `cite`-Eintrag wieder.

![texshop_image kopie](https://cloud.githubusercontent.com/assets/10049662/10914518/1d49961e-8253-11e5-8b6a-37e85cb5096c.jpg)

2) Im Falle der Option `lexika` müssten die Einträge aus der Bibliographie fehlen, stattdessen sollte eigentlich das Lexikon an sich aufgeführt werden. In dem Fall unter *Abkürzungen*:

ThesCRA     Thesaurus Cultus et....

Womöglich sollten wir hierfür auch das zum @inreference gehörige @reference definieren.

**Comment by LukasCBossert** [comment]
Stimmt. habe das soeben (vorläufig?) gefixt. Schau mal rein in den Commit.

**Comment by LukasCBossert** [comment]
zu deinem 2. Punkt. Du hast Recht, es ergibt durchaus  Sinn, dass, wenn Option `lexika` gewählt ist, die Einträge aus der Bibliographie rausfliegen. 

Möchte man dies nicht händisch machen (wie es jetzt der Fall ist), dann müsste man - so vermute ich - hier etwas verändern:
```
\newbibmacro*{cite:bib}{%
    \ifbool{cbx:lexikon}
      {\usebibmacro{cite:bib:lexikon}}
      {\iffieldundef{shorthand}
        {\ifnameundef{labelname}%
           {\usebibmacro{cite:label}
            \setunit{\labelyeardelim}}%
           {\printnames{labelname}%
            \setunit{\nameyeardelim}}%
         \usebibmacro{cite:year}}%
        {\printfield{shorthand}}}}%
```
Es muss gesagt werden, dass, wenn `bbx:lexika` lösche die Einträge mit `cbx:lexikon` .

**Comment by giovannotti** [comment]
…ja, und trage dafür den Lexikontitel (als Shorthand) in die Liste ein.

**Comment by LukasCBossert** [comment]
```
\newbibmacro*{cite:bib}{%
\ifboolexpr{bool{cbx:lexikon} and bool {bbx:lexika}}{%
%<--- Hier muss die Bedingung rein "Lösche Eintrag"		
	}{%
      {\iffieldundef{shorthand}
        {\ifnameundef{labelname}%
           {\usebibmacro{cite:label}
            \setunit{\labelyeardelim}}%
           {\printnames{labelname}%
            \setunit{\nameyeardelim}}%
         \usebibmacro{cite:year}}%
        {\printfield{shorthand}}}}}%
```

In diese Richtung könnte es erstmal gehen. Jetzt wird das Label schonmal gelöscht.

**Comment by LukasCBossert** [comment]
Vielleicht funktioniert es u.a. auch damit 
```
\defbibenvironment{bibliography}
  {\list
     {\usebibmacro{labelwidthbib}}
     {\setlength{\labelwidth}{\shorthandwidth}%
      \setlength{\leftmargin}{\labelwidth}%
      \setlength{\labelsep}{\biblabelsep}%
      \addtolength{\leftmargin}{\labelsep}%
      \setlength{\itemsep}{\bibitemsep}%
      \setlength{\parsep}{\bibparsep}%
      \renewcommand*{\makelabel}[1]{##1\hss}}}
  {\endlist}
  {%
  \ifboolexpr{bool{cbx:lexikon} and bool {bbx:lexika}}{}{%
  \item\usebibmacro{kicklabel}}%
  }
```
(Rest siehe Commit)

**Comment by moewew** [comment]
Wie wollt ihr denn generell `@inreference`s behandeln? Gibt es überhaupt welche, die nicht `cbx:lexikon` sind? Kann man diesen Schalter vielleicht einsparen?
Wenn ja kann man vielleicht abhängig von `bbx:lexika` einfach nur

```
\ExecuteBibliographyOptions[inreference]{skipbib=true}
``` 

setzen?

Ich finde es etwas unschön, das `\item` so von irgendwelchen Schaltern abhängig zu machen.

**Comment by LukasCBossert** [comment]
Es gibt `@inreferences`, die nicht `cbx:lexikon` sind, auch wenn die meisten diesen Schalter haben.

**Comment by LukasCBossert** [comment]
Kann man ein 
```
\ExecuteBibliographyOptions[inreference]{skipbib=true}
```
in Abhängigkeit von `\ifboolexpr{bool{cbx:lexikon} and bool {bbx:lexika}` setzen?

**Comment by moewew** [comment]
Mhh, ich glaube `\ExecuteBibliographyOptions[inreference]{skipbib=true}` kann man nicht auf Basis von `\ifboolexpr{bool{cbx:lexikon} and bool {bbx:lexika}` setzen. Man könnte das natürlich mit `bibcheck`s lösen.

**Comment by LukasCBossert** [comment]
Bleibt noch offen, wie bei `\ifboolexpr{bool{cbx:lexikon} and bool {bbx:lexika}` der `booktitle` (bspw: `ThesCra-kurz`) mit dem `@string` `...-kurz` und `...-lang` in das Abkürzungsauflösungsverzeichnis kommt.
Bei `CIL` ist das einfach, denn das wird direkt zitiert.
Kann man hier auch mit  der `related`-Funktion arbeiten?

**Comment by moewew** [comment]
Wenn ihr `crossref` benutzt und das Lexikon auch einen eigenen Eintrag in der `.bib`-Datei hat, dann kann das automatisch in die Bibliographie gesetzt werden, obwohl der Eintrag nicht direkt zitiert wurde (`mincrossrefs` heißt die Option, wenn ich mich recht entsinne).

Ich denke aber, dass man soetwas auch wie mit `shortjournal` und `shortseries` regeln könnte. Dann müsste aber ein Feld `shortbooktitle` erfinden und in der `.bib` dazutun ...

**Comment by LukasCBossert** [comment]
```
@Inreference{Rosenberger_2012,
  Title                    = {Öffentlich/privat bei den Römern},
  Author                   = {Rosenberger, Veit},
  booktitle                = ThesCRA-kurz,
  Pages                    = {11--16},
  Volume                   = {8},
  Year                     = {2012},
  related={ThesCRA},
  Bookpagination           = {column},
  Keywords                 = {lexikon},
  Options                  = {lexikon}
}

@Reference{ThesCRA,
  Title                    = ThesCRA-lang,
  Editor                   = {{Fondation pour le Lexicon Iconographicum Mythologiae Classicae}},
  Year                     = {2004--2012},
  Keywords                 = {Sigel},
  Options                  = {corpus},
  Shorthand             = ThesCRA-kurz,
}
```

Funktioniert soweit. 
Jedoch würde ich die Beziehung abschalten, wenn eben der Schalter `lexika` nicht aktiviert ist.
Die Änderung in 
```
\DeclareBibliographyDriver{inreference}{%
\usebibmacro{bibindex}%
 \usebibmacro{begentry}%
\ifboolexpr{bool{cbx:lexikon} and bool {bbx:lexika}}%
 			{\printfield{booktitle}%
  				\setunit{\addspace}\printfield{volume}%
  				 \setunit{\addspace}\printfield[parens]{year}%
  				\setunit{\addspace}\printfield{postnote}%
  				\setunit{\addspace}\printtext{s\adddot\addnbthinspace v\adddot}%
  				\setunit{\addspace}\printfield{title}%
  				\setunit{\addspace}\printtext[parens]{\c@uniquename=1 \printnames{labelname}}%
 } 				
{%
  			\usebibmacro{author}%
  			\setunit*{\labelnamepunct}\newblock%
  			  	\usebibmacro{reftitle}%
  				\newunit\newblock%
				 \usebibmacro{in:}%
				 \newunit\newblock%
			  \usebibmacro{booktitle+volume+editor}%
  \setunit{\addspace}%
   \usebibmacro{series+number}%
  \setunit*{\addspace}\newblock%
  \usebibmacro{location+edition+year}%
  \setunit{\addspace}%
  \ifbool{bbx:jahrreihe}{%
    \newunit\usebibmacro{series+number}\setunit{\addcomma\addspace}}{}%
  \setunit*{\addspace}\newblock%                  
  \usebibmacro{pages}%
  \setunit{\addspace}%
  \usebibmacro{addendum}%
  \usebibmacro{doi+eprint+url}%
 \setunit{\addperiod\addspace}%
  \usebibmacro{signatur}}%
  \newunit\newblock
\ifboolexpr{bool{cbx:lexikon} and bool {bbx:lexika}}{\iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}%
  \usebibmacro{savestuff}}{}%
  \usebibmacro{finentry}%
}
```
hat leider nicht geholfen.

**Comment by moewew** [comment]
Was ist denn ein Beispiel für einen Eintrag, der `@inreference` ist aber nicht `cbx:lexikon`? Ist dafpr vielleicht ein anderer Typ sinnvoller?

**Comment by LukasCBossert** [comment]
Zugegeben sind 95% meiner genutzten `@inreference`s mit `lexikon`. 
Dennoch:
```
@Inreference{Booms_2014,
  Title                    = {Architecture, Roman},
  Author                   = {Dirk Booms},
  Editor                   = {Claire Smith},
  Pages                    = {480--492},
  Publisher                = {Springer},
  Year                     = {2014},
  Booktitle                = {Encyclopedia of Global Archaeology},
}

@Inreference{Weinbrenner_1914,
  Title                    = {Rennbahn},
  Author                   = {Weinbrenner},
  Editor                   = {Lueger, Otto},
  Pages                    = {636--637},
  Location                 = {Stuttgart},
  Number                   = {2},
  Volume                   = {9},
  Year                     = {1914},
  Booktitle                = {Lexikon der gesamten Technik und ihrer Hilfswissenschaften},
}
```
Aber vielleicht ist es besser für diese Einträge `@book` zu verwenden. Das würde glaub ich einiges mit dem Code erleichtern!?

**Comment by moewew** [comment]
Die Frage ist halt, ob man da sagen kann, dass diese Werke anders funktionieren als eine normale `@inreference`, `@incollection` würde wohl auch passen. Warum haben die denn kein `cbx:lexikon`, wie unterscheiden sie sich vom Rest?

**Comment by LukasCBossert** [comment]
Ich stelle fest, dass es nicht notwendig ist die `related`-Funktion bei `bbx:lexika`abzuschalten, da in beiden fällen das Kürzel (`ThesCRA`) auftaucht, das aufgelöst werden soll/kann. Daher funktioniert es mit dem Code oben sehr gut.

**Comment by LukasCBossert** [comment]
Die Unterscheiden sich vor allem dadurch, dass sie nicht zu den Standardlexika in den Altertumswissenschaften (allen voran Archäologie und Alte Geschichte - aber auch Philologie) gehören, die auf diese Art anzugeben sind.
Zu diesen gehören die Lexika:
* DNP - Der Neue Pauly
* RE - Realencyclopädie der classischen Altertumswissenschaften
* LTUR - Lexicon Topographicum Orbis Romae
* LIMC - Lexicon Iconologicae Mythologicae Classicae
* ThesCRA - Thesaurus Cultus et Rituum (oder so?!)
* ThLL - Thesaurus Linguae Latinae
* ThLG - Th.. Graecae
* PPP - Pompeji Pitturae (oder so)
* PPM - Pompeji Mosaice
* KlP - Kleiner Pauly

Es sind also durchaus einige - vielleicht wäre es dann wirklich sinnvoller alle anderen über `@incollection` zu definieren. Der Eintrag `Weinbrenner_1914`zeigt, dass bspw. das Feld `number`berücksichtigt werden sollte).


***
Jetzt habe ich nochmals nachgeschaut (https://www.dainst.org/documents/10180/70593/01_Schlagwortliste_quer.pdf/60686d03-44a0-4fc0-a614-136c50257a12) - dort steht "Lexikon mit Bandnummer, Erscheinungsjahr in Klammern, Seite/Spalte, Stichwort mit s. v. und Namen des Autors in Klammern" - bzw. "möglich ist auch die Verwendung eines Kurzzitates nach dem Autor-Jahr-System mit Auflösung im Literaturverzeichnis"

Das heißt also, dass auch die Einträge `Booms_2014` und `Weinbrenner_1914` in Abhängigkeit des Schalters `bbx:lexika` wie `cbx:lexikon` angezeigt werden können. Damit könnte `cbx:lexikon` rausfliegen und `@inreferences` einheitlich entweder wie jetzt bei `cbx:lexikon` oder im Autor-Jahr-System angezeigt werden.

Das vereinfacht ebenfalls die Programmierung. Die `related-Funktion` kann für die abzukürzenden Lexika (siehe Liste oben) bestehen bleiben, damit diese aufgelöst werden.

**Comment by giovannotti** [comment]
Finde ich gut! Macht es weniger kompliziert für den Benutzer.

**Comment by LukasCBossert** [comment]
Ich warte noch auf eine "offizielle" Bestätigung seitens des Deut. Arch. Inst., dass alle Lexika im Sinne von `cbx:lexikon` angezeigt werden können, dann setze ich mich an die Umsetzung.

**Comment by LukasCBossert** [comment]
Da das bei #48 genannte Problem mit der Anzeige in der Bibliographie gelöst wurde, stellt sich jetzt nur die Frage, wie "schlimm" es ist, wenn bei '\DeclareBibliographyDriver{inreference}', das 
```
\iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}%
```
rausfliegt. Denn wie ich sehe, besteht intern die Verknüpfung dennoch, aber es darf in der Bibliographie nichts stehen (daher ist es momentan auskommentiert).

**Comment by moewew** [comment]
Mhh, ich kann mir gerade keinen Fall vorstellen, wo das ein Problem sein soll. Aber vielleicht verstehe ich nicht ganz, worauf Du hinaus willst. In den Beispielen gibt es kein `@inreference` mit `related` (und ich sehe auch nicht, wo das sinnvoll sein sollte; `crossref`waäre vielleicht sinnvoll, aber das ist was anderes)?

**Comment by LukasCBossert** [comment]
Sorry, mein Fehler. 

```
@Inreference{Rosenberger_2012,
  Title                    = {Öffentlich/privat bei den Römern},
  Author                   = {Rosenberger, Veit},
  booktitle                = ThesCRA-kurz,
  Pages                    = {11--16},
  Volume                   = {8},
  Year                     = {2012},
  related={ThesCRA},
  Bookpagination           = {column},
  Keywords                 = {lexikon},
  Options                  = {lexikon}
}

@Reference{ThesCRA,
  Title                    = ThesCRA-lang,
  Editor                   = {{Fondation pour le Lexicon Iconographicum Mythologiae Classicae}},
  Year                     = {2004--2012},
  location = {Los Angeles},
  Keywords                 = {Sigel},
  Options                  = {corpus},
  Shorthand             = ThesCRA-kurz,
}

```

Damit wird jetzt bei `Rosenberger_2012` auf `ThesCRA` verwiesen und sobald `Rosenberger_2012` zitiert wird, taucht auch `ThesCRA` auf. 
Würde es sich besser eigenen mit `crossref` bspw. auf die `shorthand` bei `ThesCRA` zuzugreifen?

Ansonsten funktioniert es wie gewünscht.

**Comment by moewew** [comment]
Ah, ich sehe gerade, dass oben ein Beispiel mit `related` war? Kann das da nicht zu `crossref` umbauen und geht dadurch was kaputt? Wenn das `related` nur für die Auflösung der Abkürzung war, war das sowieso eher eine sehr großzügige Auslegung dessen, was `related` normal macht. Allerdings könntet ihr mit einem eignen `relatedtype` vielleicht soetwas ohne weitere Probleme erreichen,

**Comment by LukasCBossert** [comment]
Was könnte bspw. ein `relatedtype={inreferenceof}` machen? Für den `inreference`-Eintrag muss "höchstens" die `shorthand` von `reference` als (momentan) `booktitle` weitergegeben werden.

**Comment by LukasCBossert** [comment]
Etwas wie:

```
\newbibmacro*{related:inreferenceof}[1]{%
  \entrydata*{#1}{%
    \renewbibmacro*{name:hook}[1]{%
      \ifnumequal{\value{listcount}}{1}
        {\begingroup
      %   \mkrelatedstring%
         \lbx@initnamehook{#1}%
         \endgroup}
        {}}%
    \printfield{shorthand}%
    \setunit{\addspace}%
}%
}
      
```

**Comment by moewew** [comment]
Ich weiß natürlich mal wieder nicht, wie es eigentlich aussehen soll. Aber mit `xref` und `mincrossrefs=1`

wird bei

```
@Inreference{Rosenberger_2012,
  Title                    = {Öffentlich/privat bei den Römern},
  Author                   = {Rosenberger, Veit},
  booktitle                = ThesCRA-kurz,
  Pages                    = {11--16},
  Volume                   = {8},
  Year                     = {2012},
  xref ={ThesCRA},
  Bookpagination           = {column},
  Keywords                 = {lexikon},
  Options                  = {lexikon}
}
```

`ThesCRA` automatisch zur Bibliographie hinzugefügt.

**Comment by LukasCBossert** [comment]
Also im Grunde funktioniert es wie gewünscht mit `related`- es geht nur darum, dass der Eintrag `ThesCRA` in der Bibliographie erscheint, wenn ein `inreference` daraus zitiert wird. Dasselbe würde ja auch mit `xref`-passieren. Mir scheint aber es dann einfacher mit `related` zu arbeiten, da keine Felder vererbt werden müssen und man die `related`-Funktion schon von `review` und `translation` her kennt und man nichts neues mehr einführen muss.
