### ISSUE TITLE
bibmacro{location+edition+year} entschlacken und Bugs beheben

### ISSUE THREAD

**Issue by giovannotti** [giovannotti/biblatex-archaeologie#68]
Wenn das Feld `location` keinen Wert besitzt, werden derzeit die Klammern nicht um das übrig bleibende Jahr gesetzt. Da das Bibmacro aufgebläht ist (der `\ifbool{bbx:verlag}` am Anfang allein bläht es sehr auf; man könnte ihn bestimmt weiter hinten [wenn dann auch vllt. öfters] einbauen), macht es Sinn das ganze Macro zu überarbeiten.

**Comment by LukasCBossert** [comment]
Ja, du hast recht. Machst du das?

**Comment by moewew** [comment]
Die Makros  `series` und `journal` kann man mit ein bisschen Zusammenstreichen der Logik zu

```
\renewbibmacro*{series}{%
  \ifboolexpr{test {\iffieldundef{shortseries}} or bool {bbx:keineabkuerzung}}
    {\printtext[seriestitle]{\printfield[titlecase]{series}}}
    {\printfield{shortseries}}}%

\renewbibmacro*{journal}{%
  \ifboolexpr{test {\iffieldundef{shortjournal}} or bool {bbx:keineabkuerzung}}
    {\printtext[journaltitle]{%
       \printfield[titlecase]{journaltitle}%
       \setunit{\subtitlepunct}%
       \printfield[titlecase]{journalsubtitle}}}
    {\printfield{shortjournal}}}
```

verkürzen.

**Comment by giovannotti** [comment]
Stimmt, ist sonst nur gedoppelter Code. Umgesetzt.

**Comment by LukasCBossert** [comment]
Sieht sehr gut aus - kann keine fehlerhafte Darstellung erkennen.
