### ISSUE TITLE
Wechsel des default -Zweig: von "master" zu "Beta-Version"?

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#7]
ich habe in Source-tree den Zweig "master" in "Beta-Version" umbenannt, aber es hat mir einfach für einen neuen Zweig erstellt (master ist bei mir in sourcetree verschwunden). 

- Hast du die Möglichkeit "Beta-Version" zum Default-Zweig zu machen?

**Comment by giovannotti** [comment]
Erledigt.

**Comment by LukasCBossert** [comment]
sehr gut. 
Ich erstelle noch ein paar Issues, die mir gerade in der Bibliographie auffallen, dann kann man die sukzessive abarbeiten.


Am 29.06.2015 um 09:31 schrieb Johannes <notifications@github.com>:

Erledigt.

**Comment by LukasCBossert** [comment]
bei mir wird noch immer angezeigt, dass „master“ default sei. Vielleicht dauert es noch ein bisschen, bis es umgestellt ist?!


Am 29.06.2015 um 09:31 schrieb Johannes <notifications@github.com>:

Erledigt.
