### ISSUE TITLE
Benutzung von subtitle

### ISSUE THREAD

**Issue by giovannotti** [giovannotti/biblatex-archaeologie#70]
Vielfach gibt es diese Reihenfolge der Titelzitation nach DAI:

*…, Roman Provincial Coinage II. From Vespasian to Domitian…*

Dies erreicht man derzeit nur durch

```
…
title = {Roman Provincial Coinage II. From Vespasian to Domitian},
…
```

Besser:

```
title = {Roman Provinicial Coinage},
volume = {II},
subtitle = {From Vespasian to Domitian},
```

Ergibt derzeit aber 

*…, Roman Provincial Coinage. From Vespasian to Domitian II…*

**Comment by LukasCBossert** [comment]
Dieses Problem löse ich dann mit

```
title = {Roman Provinicial Coinage},
volume = {II. From Vespasian to Domitian},
```

Dann sollte das gewünschte Ergebnis rauskommen.

**Comment by giovannotti** [comment]
Klar, aber auch nur geringfügig besser. Genau dafür wäre `subtitle` super. Ist ja schnell umzusetzen.

**Comment by LukasCBossert** [comment]
Aber ist jeder Subtitle bei angegebener `volume` zugleich der `Titel` des "Unterbandes" ?

Hast du es schonmal mit `maintitle`versucht? 

```
maintitle = {Roman Provinicial Coinage},
volume = {II},
title = {From Vespasian to Domitian},
```

Keine Ahnung was da rauskommt.

**Comment by LukasCBossert** [comment]
Schau mal in der deutschen biblatex-Dokumentation Seite 37--38.
Dort ist es beschrieben. mit `maintitle` müsste es funktionieren.

**Comment by giovannotti** [comment]
Hast recht. Maintitle macht hier viel mehr Sinn, genau dafür ist das ja da. Das andere ist Quatsch.
Aber ergibt:

*…Roman Provincial Coinage, I: From the death of Caesar to the death of Vitellius I…*

```
	Maintitle = {Roman Provincial Coinage},
	Options = {corpus},
	Shorthand = {RPC I},
	Title = {From the death of Caesar to the death of Vitellius},
	Volume = {I},
```

**Comment by LukasCBossert** [comment]
schick mal einen screenshot.

**Comment by LukasCBossert** [comment]
Ist das Komma und der Doppelpunkt falsch? Da scheint `volume` zweimal aufzutauchen?!

**Comment by LukasCBossert** [comment]
man muss dann das `volume` im `bibmacro`von `mainttitle+title` umbauen und dann sagen, dass er es nicht mehr nach dem Titel ausgibt.

**Comment by giovannotti** [comment]
ja, genau wie du sagst. Ist keine große Nummer, aber ich setz mich erst im neuen Jahr ran ;-)

**Comment by LukasCBossert** [comment]
cogito, consummatum est --> https://github.com/giovannotti/biblatex-archaeologie/commit/097ea1c8343a5e53ce3747d4afa2e8ae963ebb18

Schau dir in der Stilbeschreibung Punkt 5.1.3 mal an :+1:  :)

**Comment by giovannotti** [comment]
Na sowas, du kommst nicht los vom Code ;)
Ich danke dir!

**Comment by LukasCBossert** [comment]
Ok. neuer Ausnahmefall:

```
@Incollection{Fentress_2003b,
  Title                    = {Cosa in the Republic and Early Empire},
  Author                   = {Fentress, Elizabeth and John Bodel and Adam Rabinowitz and Rabun Taylor},
  Booksubtitle             = {Excavations 1991--1997},
  Booktitle                = {An Intermittent Town},
  Editor                   = {Fentress, Elizabeth},
  Location                 = {Ann Arbor, Mich.},
  Number                   = {2},
  Pages                    = {13--62},
  Publisher                = UMP,
  Series                   = MemAmAc-lang,
  Shortseries              = MemAmAc-kurz,
  Year                     = {2003},
  Volume                   = {V},

  Language                 = {english},
  Maintitle                = {Cosa},
}
```

ergibt:

<img width="1285" alt="bildschirmfoto 2015-11-18 um 16 21 31" src="https://cloud.githubusercontent.com/assets/12896078/11245017/eef43462-8e10-11e5-85a0-acdd510b4347.png">

da muss man nochmals nachjustieren. 
ggf. über ein `\ifentrytype{inbook}`...

**Comment by LukasCBossert** [comment]
Scheint mir nun mit 
```
\renewbibmacro*{maintitle+booktitle}{%
  \iffieldundef{maintitle}
    {}
    {\usebibmacro{maintitle}%
     \iffieldundef{volume}
       {\setunit{\maintitlepunct}}% 
       {\setunit{\addspace}
        \printfield{volume}%
        \printfield{part}%
        \setunit{\adddot\space}}}%
  \usebibmacro{booktitle}%
  \newunit}
```
gefixt zu sein.
