### ISSUE TITLE
Origlocation und Origyear fixen

### ISSUE THREAD

**Issue by giovannotti** [giovannotti/biblatex-archaeologie#74]
Origyear scheint nicht definiert zu sein und mit Origdate und Origlocation zu kollidieren.

```
@book{mccloud2001,
	Author = {McCloud, Scott},
	Edition = {ver{\"a}nderte deutsche Neuausgabe},
	Location = {Hamburg},
	Origdate = {1993},
	Origlocation = {New York},
	Origtitle = {Understanding Comics},
	Origyear = {1994},
	Title = {Comics richtig lesen. Die unsichtbare Kunst},
	Year = {2001},
}
```
ergibt:
S. McCloud, Comics richtig lesen. Die unsichtbare Kunst, veränderte deutsche Neuausgabe (Hamburg 1993; Nachdr. Hamburg 2001)

und ohne `origdate`: 

```
@book{mccloud2001,
	Author = {McCloud, Scott},
	Edition = {ver{\"a}nderte deutsche Neuausgabe},
	Location = {Hamburg},
	Origlocation = {New York},
	Origtitle = {Understanding Comics},
	Origyear = {1994},
	Title = {Comics richtig lesen. Die unsichtbare Kunst},
	Year = {2001},
	}
```
ergibt:
S. McCloud, Comics richtig lesen. Die unsichtbare Kunst, veränderte deutsche Neuausgabe (New York Hamburg 2001)

**Comment by LukasCBossert** [comment]
Stimmt. `origlocation` wird nicht ausgelesen, wenn man ein `origyear` auch hat.
Mir ist aber nicht klar, was du mit dem `origdate` oben angeben möchtest, wenn du schon ein `origyear` hast?
Aber sonst sollte bei deinem zweiten Beispiel das `origyear`angegeben werden. 

```
@Incollection{Reinhardt_1904,
  Title                    = {Baulichkeiten für den Sport},
  Author                   = {Reinhardt, Robert},
  Booktitle                = {Handbuch der Architektur},
  Location                 = {Stuttgart},
  Pages                    = {172--200},
  Publisher                = {Alfred Kröner},
  Subtitle                 = {Reit- und Rennbahnen},
  Year                     = {1904},
  Edition                  = {3},
  Volume                   = {4. Halbband, Heft 2: Gebäude für Erholungs-, Beherbungs- und Vereinszwecke},
  Bookpagination           = {column},
  Origyear                 = {1894},
  Origlocation             = {Darmstadt},

}
```

ergibt:

<img width="1131" alt="bildschirmfoto 2015-12-02 um 18 32 58" src="https://cloud.githubusercontent.com/assets/12896078/11538726/84dee5b8-9923-11e5-9019-11727900357a.png">

also nur die fehlerhafte `origlocation`

**Comment by giovannotti** [comment]
Das war nur Geteste und etwas unglücklich ausgedrückt :-) Es muss nur `origlocation` gefixt werden.

**Comment by LukasCBossert** [comment]
Gelöst.
siehe Commit: https://github.com/giovannotti/biblatex-archaeologie/commit/0f84db1ca61e5a7997ebe755c73977d22d4ed284
