### ISSUE TITLE
Darstellung im Literaturverzeichnis

### ISSUE THREAD

**Issue by dirkseidensticker** [giovannotti/biblatex-archaeologie#77]
Hallo,

ich bin heute auf Ihre Umsetzung der Zitations- und Bibliographievorgaben gefunden. Leider entspricht meine Ausgabe des Literaturverzeichnisses nicht der 'zweispaltigen' Gestaltung, die im dem Paket zugeordneten PDF abgebildet ist (S. 34 ff.). Bei mir werden die Kurzzitate durch einen Zeilenumbruch vom leicht eingerückten Zitat getrennt. Wie erhalte ich eine Ausgabe, in der das Kurzzitat auf der gleichen Zeile sitzt (ähnlich wie in Ihrem PDF und wie es alphabetic macht)? Habe ich eine Option übersehen?

Vielen Dank und mit besten Grüßen

Dirk Seidensticker

![archaeologie-Variante](https://cloud.githubusercontent.com/assets/6630811/12298351/e944a72c-ba11-11e5-9424-94ecd3492cac.png)

![alphabetic-Variante](https://cloud.githubusercontent.com/assets/6630811/12298355/edd32eda-ba11-11e5-9ad2-e95d83181da2.png)

![Ihre Vorlage](https://cloud.githubusercontent.com/assets/6630811/12298441/66ef55fa-ba12-11e5-9108-bd743dae826c.png)

**Comment by LukasCBossert** [comment]
Der Abstand wird standardmäßig über die Länge der längsten `shorthand` erzeugt. Da wir ausgingen, dass bei den altertumswissenschaftlichen Texten sich (immer) ein antiker Autor (welcher mittels `shorthand` ausgegeben wird) befindet, haben wir uns die Frage nicht gestellt, wenn man nur moderne Literatur zitiert. 
Aktuell sieht es in der bbx-Datei so aus:
```
\setlength{\labelwidth}{\shorthandwidth}
```

Ich habe es nicht ausprobiert, aber mit der Re-definition von `\labelwidth`sollte man dies individuell ändern können. Bspw.
```
\setlength{\labelwidth}{4em}
```

**Comment by LukasCBossert** [comment]
Hiermit kann man es individuell einstellen, falls die `shorthandwidth` zu lang oder zu kurz ist:

```
\setlength{\shorthandwidth}{9em}
```

`9em` ist hier nur ein Beispielswert, der mit anderen Längenangaben (`4pt`,etc) ersetzt werden kann.

**Comment by LukasCBossert** [comment]
Soll als Option in den Stil aufgenommen werden, sodass man in der Präambel den Abstand individuell wählen kann.

**Comment by LukasCBossert** [comment]
Ist im Update 1.3 (2016-01-31) enthalten.
