### ISSUE TITLE
Abstand in der Bibliographie zwischen Label und Eintrag

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#79]
Der bisherige Code produziert nun mit der aktuellen `biblatex`-Version nicht mehr die bisherige Bibliographie.

```
\newsavebox\arch@labelbox%

\newbibmacro{labelwidthbib}{%
  \begingroup%
    \DeclareFieldFormat{bibhyperref}{##1}%
   \csuse{blx@hook@cite}%
    \csuse{blx@hook@citekey}%
    \defcounter{maxnames}{\blx@maxcitenames}%
    \usebibmacro{cite}%
  \endgroup%
}   


\newbibmacro{kicklabel}{% 
  \sbox\arch@labelbox{\usebibmacro{labelwidthbib}}%
  \global\togglefalse{blx@insert}%
  \ifdim\shorthandwidth<.9\wd\arch@labelbox\leavevmode\newline\fi%
  }

\defbibenvironment{bibliography}%
  {\list%
     {\usebibmacro{labelwidthbib}}%
     {\setlength{\labelwidth}{%
     		\ifbool{bbx:width}{\width}{\shorthandwidth}}%
      \setlength{\leftmargin}{\labelwidth}%
      \setlength{\labelsep}{\biblabelsep}%
      \addtolength{\leftmargin}{\labelsep}%
      \setlength{\itemsep}{\bibitemsep}%
      \setlength{\parsep}{\bibparsep}%
      \renewcommand*{\makelabel}[1]{##1\hss}}}%
  {\endlist}
  {\item\usebibmacro{kicklabel}}
```

Mir ist nicht klar, was sich nun mit dem Update verändert hat.

**Comment by moewew** [comment]
Ich wüsste jetzt nichts, was da direkten Einfluss drauf haben sollte. Hast Du ein Beispieldokument, das vorher funktionierte und jetzt nicht mehr das richtige tut (am besten mit einer Becshreibung, was das Richtige ist)? Ich habe gerade mit dem Code aus der 2.0-Branch herumgespielt. Da kommt immer wieder `\shorthandwidth` vor, das würde ich vielleicht lieber nicht verwenden und immer eine bestimmte Vorgabe nehmen

```
\newsavebox\arch@labelbox%

\newbibmacro{labelwidthbib}{%
  \begingroup%
    \DeclareFieldFormat{bibhyperref}{##1}%
    \csuse{blx@hook@cite}%
    \csuse{blx@hook@citekey}%
    \defcounter{maxnames}{\blx@maxcitenames}%
    \usebibmacro{cite}%
  \endgroup%
}   

\newlength{\labwidthsameline}
\setlength{\labwidthsameline}{50pt}

\newbibmacro{kicklabel}{% 
  \sbox\arch@labelbox{\usebibmacro{labelwidthbib}}%
  \global\togglefalse{blx@insert}%
  \ifdim\wd\arch@labelbox>\labwidthsameline\leavevmode\newline\fi%
}

\defbibenvironment{bibliography}%
  {\list%
     {\usebibmacro{labelwidthbib}}%
     {\setlength{\labelwidth}{\labwidthsameline}%
      \setlength{\leftmargin}{\labelwidth}%
      \setlength{\labelsep}{\biblabelsep}%
      \addtolength{\leftmargin}{\labelsep}%
      \setlength{\itemsep}{\bibitemsep}%
      \setlength{\parsep}{\bibparsep}%
      \renewcommand*{\makelabel}[1]{##1\hss}}}%
  {\endlist}
  {\item\usebibmacro{kicklabel}}
```
gibt zumindest bei mir erträgliche Ergebnisse.

**Comment by LukasCBossert** [comment]
Dein Code macht wieder das, was es soll. Das Problem scheint mir darin gelegen zu haben das `\shortandwidth`(nicht mehr?) ausgelesen wird, weshalb es keine Grundeinstellung mehr gab. Dies ist mir erst mit dem Update auf die letzte biblatex-Version aufgefallen.

Deinen Code habe ich eingebaut und etwas modifiziert


```
\newbool{bbx:width}%abstand

\newlength{\labwidthsameline}
\setlength{\labwidthsameline}{3em}

\DeclareBibliographyOption{width}[]{%
			\csuse{booltrue}{bbx:width}	
			\setlength{\labwidthsameline}{#1}}
```

Mit der zusätzlichen Option `width` kann man den Abstand regulieren, wenn es keine `shorthand` gibt, oder die Länge der längsten `shorthand` zu lang ist.
Dies funktioniert prima.

Jetzt müsste man die Grundeinstellung auf etwas wie 
```
\setlength{\labwidthsameline}{\shorthandwidth}
```
bringen können. 

Ansonsten habe ich nur den Faktor `0.9` bei `\newbibmacro{kicklabel}{% 
  \sbox\arch@labelbox{\usebibmacro{labelwidthbib}}%
  \global\togglefalse{blx@insert}%
  \ifdim.9\wd\arch@labelbox>\labwidthsameline\leavevmode\newline\fi%
}` wieder eingebaut. 

Änderung im letzten commit https://github.com/giovannotti/biblatex-archaeologie/commit/2a799f47c032afb162b0a7d7dcc31f8b90ff16fc

**Comment by moewew** [comment]
Wahrscheinlich ist `shorthandwidth` auf `0` initialisiert. Die Frage ist, warum das die Grundeinstellung sein sollte. Wenn ich mich nicht irre, ist das die Länge des längsten Shorthands. Wenn kein Eintrag ein Shorthand hat, dann ist das problematisch. Selbst wenn es Einträge mit Shorthands gibt, würde ich einen Mindestabstand verlangen, denn die können bisweilen recht kurz sein.

Du könntest ein Minimum und ein Maximum bestimmen. Liegt shorthandwidth unter dem Minimum, wird der Minimumeinzug gesetzt, ist `shorthandwidth` zwischen den beiden Werten, passen wir uns `shorthandwidth` an und schließlich ist Maximum der maximale Einzug.
Vielleicht soetwas (nicht getestet)

```
\setlength{\labelwidth}{\labwidthsamelinemin}%
\ifdim\labwidthsamelinemin<\shorthandwidth
  \setlength{\labelwidth}{\labwidthsameline}%
\fi
\ifdim\labwidthsamelinemax<\shorthandwidth
  \setlength{\labelwidth}{\labwidthsamelinemax}%
\fi
```

**Comment by LukasCBossert** [comment]
Ich habe nochmals nachgedacht und mir das angeschaut, du hast recht, es macht keinen Sinn von der Shorthand ausgehend die Länge bestimmen zu wollen. Es ist wohl klüger (und einfacher) einen Standardwert zu definieren, von dem der Anwender nach Belieben (mit `width=xy`) abweichen kann.

**Comment by LukasCBossert** [comment]
Es gibt allerdings noch eine Sache hinsichtlich "Länge", die ich nicht verstehe:

```
\defbibcheck{shortjournal}{%
    \iffieldundef{shortjournal}{\skipentry}{}%
    \iffieldundef{journaltitle}{\skipentry}{%
        \ifcsdef{\strfield{journaltitle}}{\skipentry}{\savefieldcs{journaltitle}{\strfield{journaltitle}}}%   
            }}
```

ergibt oft

<img width="980" alt="screen shot 2016-03-16 at 12 56 27" src="https://cloud.githubusercontent.com/assets/12896078/13811543/be2173c2-eb76-11e5-8828-dd4b4527a60d.png">

Mir ist nicht ersichtlich, ob dies am obigen Code oder an den Bib-Einträgen liegt, wobei mir dann unklar ist, wie ein Bibeintrag sich auf den Abstand zwischen Kürzel und Ausschreibung einwirken kann.

**Comment by moewew** [comment]
Das folgende Beispiel reproduziert das Problem.

```
\documentclass[a4paper,english,ngerman]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}
\usepackage[style=archaeologie]{biblatex}
\usepackage{hyperref}

\addbibresource{archaeologie.bib}
\begin{document}
\cite{Bossert_2016,Taylor_2008}
\printbiblist{shortjournal}
\end{document}
```

Du wirst feststellen, dass Taylors `shortjournal` das gar nicht mal so kurze `Journal of the Society of Architectural Historians`  ist, dieses Monstrum wird aber trotzdem bei der Längenberechnung von `shortjournalwidth` berücksichtigt (obwohl es in der Liste letztendlich sinnvollerweise nicht vorkommt). Wäre es möglich, hier einfach `journal(title)` zu nutzen?

**Comment by LukasCBossert** [comment]
Oh man, du hast absolut recht und ich habe das nicht gesehen.... Danke!
