### ISSUE TITLE
extra-bibliographie "dai-abkuerzungen.bib"

### ISSUE THREAD

**Issue by LukasCBossert** [giovannotti/biblatex-archaeologie#80]
Die extra Bibliographie (dai-abkuerzungen.bib) wird beim Kompilieren im Systemordner (zumindest bei MacOS) nicht gefunden, sodass diese Datei zusätzlich immer im Hauptordner der entsprechenden tex-Datei liegen muss.

Der Versuch die Bibliographie nur optional (mit `strings=false`) zu berücksichtigen (wenn man die in der bib-Datei liegenden `@strings` nicht benötigt), funktioniert  zwar, aber sobald `strings=true` gesetzt wird,
wird die Datei benötigt.

Mit 
```
\IfFileExists{dai-abkuerzungen.bib}{\addbibresource{dai-abkuerzungen.bib}}{\addbibresource[location=remote]{https://www.ctan.org/tex-archive/macros/latex/contrib/biblatex-contrib/archaeologie/dai-abkuerzungen.bib}}}
```
wurde versucht (wenigstens bei bestehender Internetverbindung) auf die Bib-Datei zuzugreifen, aber leider funktioniert dies auch nicht.
@moewew: Welche Möglichkeit gibt es sonst, dass die Bib-Datei aus dem Systemordner geladen wird?

**Comment by moewew** [comment]
Eigentlich sollten `.bib`-Dateien in den Systemordnern auffindbar sein, die `biblatex-examples.bib` in `bibtex/bib/biblatex/biblatex-examples.bib` wird ja auch gefunden. Es kann aber sein, dass man dafür die file name database aktualisieren muss.

**Comment by LukasCBossert** [comment]
auch ein `sudo mktexlsr ` hilft leider nicht. `dai-abkuerzungen.bib` wird nicht gefunden.

**Comment by moewew** [comment]
Es kann sein, dass `.bib`-Dateien in `/bibtex/bib/` liegen müssen.

**Comment by LukasCBossert** [comment]
aha, das müsste dann extra auf CTAN aufgespielt werden, wenn es für alle global gelten soll?!

**Comment by LukasCBossert** [comment]
wow - lokal funktioniert es. dann ist das die Lösung
